### ISSUE TITLE
Update supported platforms to show supported architectures

### ISSUE THREAD

**Issue by itsjustkevin** [flutter/website#10136]
### Describe the problem

The [supported deployment platforms](https://docs.flutter.dev/reference/supported-platforms) page does not specify which architectures are supported.

### Expected fix

Show supported platforms and architectures.

Example: Windows Arm64, X86 etc.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Yeah, this was on my agenda for the next release where it will start to become more relevant. Thanks for filing an issue for it!

In the redesign I also planned to document supported deployment platforms on the beta channel, as we encourage developers to use it, but it also will give developers a heads up of any changes. That will also enable the relevant platform teams to keep that up to date as they make changes instead of a few months later when we make a stable release.

We'll have to explores some new designs :D
