### ISSUE TITLE
TypeError: Class constructor IndexedDBLocalPersistence cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Nazeerpanem786** [flutter/website#10232]

**Comment by atsansone** [comment]
@Nazeerpanem786: Thank you for your submission? Can you provide additional context so we can make a fix? On which page does this appear? Thanks!

**Comment by parlough** [comment]
Checking back in on this, thanks again for the issue!

Please note this repository is for the [Flutter documentation website](https://docs.flutter.dev/). If your issue is related to Flutter or its docs, please reply or open a new issue with more information.

As you mentioned `IndexedDBLocalPersistence`, it seems you might be having an issue with web code or perhaps Firebase. If so, try to report the issue to the most relevant project.

Thanks again!
