### ISSUE TITLE
[PAGE ISSUE]: 'Scrolling widgets'

### ISSUE THREAD

**Issue by syntacticsugarllc** [flutter/website#10259]
### Page URL

https://docs.flutter.dev/ui/widgets/scrolling/

### Page source

https://github.com/flutter/website/tree/main/src/ui/widgets/scrolling.md

### Describe the problem

You've included NotificationListener class here, which I believe is a mistake. 

### Expected fix

Remove NotificationListener from the scrolling widgets page. 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for opening an issue and considering this!

Often `NotificationListener` ends up being quite relevant for scrolling due to various [`ScrollNotification`](https://api.flutter.dev/flutter/widgets/ScrollNotification-class.html) sent during scrolling.

Potentially the `NotificationListener` API docs should have some more cross-links or examples, but my feeling is that it's still a useful part of the Scrolling category in the widget catalog. What do you think?

If you think the [`NotificationListener`](https://api.flutter.dev/flutter/widgets/NotificationListener-class.html) API docs should be expanded though, please open an issue on the [`flutter/flutter` repository](https://github.com/flutter/flutter/issues) with details on what you think would be helpful. Thanks :D
