### ISSUE TITLE
Why can't Chinese users directly use the download link to download the flutter SDK

### ISSUE THREAD

**Issue by zhAvery** [flutter/website#10257]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

Why can't Chinese users directly use the download link to download the flutter SDK? In the case of Chinese ip, please give the download link.

### Expected fix

给出相应的下载sdk链接，我的flutter在运行flutter upgrade后就一直提示我“If you're located in China, please see this page:
  https://flutter.dev/community/china” 我想直接进官网下载sdk都找不到下载的地方

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by AmosHuKe** [comment]
China Mirror website: https://flutter.cn/docs/get-started/install
Flutter SDK: https://flutter.cn/docs/release/archive

**Comment by parlough** [comment]
Chinese users can technically try to use the normal download links, however since they are hosted on Google servers, the endpoints are usually inaccessible from within mainland China. If you prefer, you can use a VPN to maintain access, but that doesn't work for everyone and might result in slower download times.

Many developers instead prefer to use a mirror site for the Flutter downloads and pub dependency, as outlined in https://docs.flutter.dev/community/china.

As `@AmosHuKe` linked to above, the `flutter.cn` mirrors are a common choice to consider.

Thanks for the issue! Let us know if you think we can improve the documentation here :)
