### ISSUE TITLE
Não consigo fazer download

### ISSUE THREAD

**Issue by LucasMarcio1** [flutter/website#10927]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/windows/index.md

### Describe the problem

Não consigo fazer donwload, pois aparece erro na tela do windows.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
According to Google translate, you can't download Flutter because an error appears. I'm sorry, but we can't provide technical support on this channel. If you find an error in the docs, please file an issue here. Otherwise, reach out to the [community](https://www.flutter.dev/community) to answer questions.
