### ISSUE TITLE
Set up flutter - android - libncurses5 not in Unbuntu 24.04 (Kubuntu)

### ISSUE THREAD

**Issue by Promis-E** [flutter/website#11252]
### Page URL

https://docs.flutter.dev/get-started/install/linux/android/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/linux/android.md

### Describe the problem

following the instructions when setting up flutter in Kubuntu (Ubuntu24.04) [https://docs.flutter.dev/get-started/install/linux/android](url) we have to installl libncurses5:amd64 . However , I cannot , and from this link on reddit it says that libncurse5 has been removed from Ubuntu 24.04 [https://www.reddit.com/r/Ubuntu/comments/1cm97bg/libncurses5dev/?tl=es-es](url)

### Expected fix

In the link from reddit quoted above there is a work around. I expect that the work around to be confirmed and the documentation updated to reflect what users should be doing

### Additional context

I discovered this when trying to set up flutter for the first time

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by surfmuggle** [comment]
I am running into the same issue with ubuntu 24. It seems that [20 & 22 were the last versions that had libncurses5](https://packages.ubuntu.com/search?keywords=libncurses5)
AFAIU from this discussion [libncurses5 package missing on 23.10](https://answers.launchpad.net/ubuntu/+source/ncurses/+question/707838) the cause is that [debian dropped support for libncurses5](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025964). 

If the docs would contain a guide or a link to adding it manually this would be great.

**Comment by parlough** [comment]
@reidbaker @cbracken Any advice here? Should we just document or link out to a workaround for installing libncurses5?

**Comment by brainwo** [comment]
I'm not on Ubuntu, but looking at the recent ppa packaged deb for Android Studio, it seems like Android Studio no longer depends on ncurses.

Download file: https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio/+files/android-studio-2024.2.2_2024.2.2.6~noble+0_amd64.deb
```
Package: android-studio-2024.2.2
Version: 2024.2.2.6~noble+0
Architecture: amd64
Maintainer: Maarten Fonville <maarten.fonville@gmail.com>
Installed-Size: 23
Pre-Depends: wget, coreutils
Depends: unzip
Suggests: libc6-i386, lib32z1
```

Download file: https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio/+files/android-studio-2020.3.1_2020.3.1.22~xenial+0_amd64.deb
```
Package: android-studio-2020.3.1
Version: 2020.3.1.22~xenial+0
Architecture: amd64
Maintainer: Maarten Fonville <maarten.fonville@gmail.com>
Installed-Size: 28
Pre-Depends: wget, coreutils
Depends: java-sdk, unzip
Recommends: libc6-i386, lib32stdc++6, lib32gcc1, lib32ncurses5, lib32z1
Suggests: default-jdk
```

**Comment by brainwo** [comment]
Seems like Android Studio no longer needs ncurses. From what I gather, it was used [for adb](<https://stackoverflow.com/questions/17005654/error-while-loading-shared-libraries-libncurses-so-5>) that was loaded alongside with Android Studio.

I uninstalled ncurses in my machine, it seems Android Studio runs just fine.

**Comment by reidbaker** [comment]
If that is the case then we can remove the documentation to install ncurses.

**Comment by parlough** [comment]
Thanks for looking in to that and clarifying @brainwo! I appreciate it :D

**Comment by SGP57** [comment]
At https://developer.android.com/studio/install today, 21/01/2026, I've installed android studio, android-studio-2025.2.3.9-linux.tar.gz.

I'm on ubuntu 24.04 and am told to install libncurses5:i386 because:
If you are running a 64-bit version of Ubuntu, you need to install some 32-bit libraries
The other additional libraries have successfully installed

Is libncurses5:i386 still needed?
