### ISSUE TITLE
[website] Korean translation

### ISSUE THREAD

**Issue by TroyTae** [flutter/website#1186]
I'm interested in this project.
So I want to translate into Korean.
I saw Chinese site for reference, but it was completely different site.
How can I work on this?

**Comment by Sfshaza** [comment]
Hi @TroyTae! Thanks for your interest!

That's something that was set up by a community in China, just as the Spanish site was set up by a Spanish-speaking community. Do you know if youu have a Korean Flutter community? 

I have asked our community outreach person whether there is a Flutter community in Korea. If so, that would be your best bet. I'm sorry I can't be more directly helpful, but I'm happy to hear your enthusiasm for Flutter!

**Comment by Sfshaza** [comment]
@TroyTae, I heard back from the Flutter community outreach person. We don't yet have a Flutter community in Korea, at least not that we're aware of, but I hope one starts up soon!

**Comment by TroyTae** [comment]
Hi @Sfshaza, Thank you for your answer!

Then I will fork this repository and translate it.
There are no Flutter communities, but I can share them through other developer communities.
I also hope to create a flutter community in Korea.

**Comment by Sfshaza** [comment]
That would be amazing, @TroyTae!  Our license allows people to do that so long as they give us attribution.  You can find the license in the footer of our site:

Except as otherwise noted, this work is licensed under a Creative Commons Attribution 4.0 International License, and code samples are licensed under the BSD License.

It would be wonderful to have a Korean version! But let me tell you that, before end of the year, we plan to reorganize our site.

**Comment by TroyTae** [comment]
@Sfshaza 
Thank you for caring me.
I will notice to you after end translation!

**Comment by TroyTae** [comment]
@Sfshaza 
Please let me know if you are going to change your site!

**Comment by Sfshaza** [comment]
You are kind, @TroyTae. :)  I will try to keep you posted, but I plan to do the work pretty much in the open.

**Comment by TroyTae** [comment]
@Sfshaza 
I'm looking forward participate of many people!
See you soon :)
