### ISSUE TITLE
[dash][IA] "Using hot reload" is under "Tools" but it isn't a tool

### ISSUE THREAD

**Issue by chalin** [flutter/website#1448]
Currently, the **Using hot reload** page is under **Development > Tools**, but "hot reload" isn't a tool.

Two options come immediately to mind: either ...

- Move "Using hot reload" elsewhere under "Development"
- Rename the "Tools" to "Tools and techniques"

Thoughts?

cc @filiph

**Comment by Sfshaza** [comment]
I suppose it could go under Development => Hot reload.  Not sure I want to add techniques to tools.

**Comment by galeyang** [comment]
I'm fine with keeping it under "Tools" because it is used along with the IDE. From the study we saw a few people put it under the larger group "Development" or a more specific group "Tool", so

> it could go under Development => Hot reload.

 @Sfshaza's suggestion also seems to be reasonable.

Question: if we'd love to follow a more strict definition for "Tools", do we also want to reconsider "Tools => Upgrading Flutter"?

cc @InMatrix

**Comment by chalin** [comment]
I propose that instead of just "Upgrading Flutter" the entries be:

- Development
  - Tools
    - Flutter SDK
      - Upgrading
      - Archive

That will give the archive page a home (#1397).

**Comment by Sfshaza** [comment]
I like Patrice's suggestion!

**Comment by galeyang** [comment]
The suggestion about upgrading looks good.
