### ISSUE TITLE
[dash][IA] Sidenav supports 3 levels, but IA has 4 levels

### ISSUE THREAD

**Issue by chalin** [flutter/website#1451]
The sidenav supports 3 levels, but IA has 4 levels, is this an issue?

**Edit:** the sidenav will be adapted to support 4 levels:

- [x] Adjust Liquid programming - #1480
- [ ] Adjust styles

cc @Sfshaza @fertolg @filiph

**Comment by Sfshaza** [comment]
This is an issue, as the current setup "hides" important docs. Can we talk about this, @galeyang?

**Comment by galeyang** [comment]
Two possible ways 

**Option 1: have our sidenav support 4 levels.** 
This means we may want to slightly adjust the design, especially the vertical line shown below.

![image](https://user-images.githubusercontent.com/5102864/46881737-42743000-ce01-11e8-853a-ee193743c013.png)

**Option 2: remove the level 4 and adjust the IA proposal**

**- Animation:** all animation docs need to be put together. Use the Animation introduction page as a entry point and list all sub-pages here
**- The pages under "Advanced UI"**: since we only have two pages with different topics now, we can directly add them as the last few items under the "User Interface".
**- The pages under "Platform-specific theming"**: it depends on long these future docs are. 


What do you think?

**Comment by Sfshaza** [comment]
We need to support 4 levels for now and in the future. We will be adding
lots of docs in the future, and this limitation would be a constant
irritation.

**Comment by fertolg** [comment]
@galeyang and @Sfshaza You can review how this looks in the following staging link: https://flutter-io-staging-1.firebaseapp.com/development/ui/advanced/gestures

Let me know if you have more comments, and feel free to reopen this issue.

**Comment by chalin** [comment]
Actually, after taking another look, the current styling is quite fine (though still _a bit_ airy for my taste :).
