### ISSUE TITLE
Issue from website page Building a form with validation

### ISSUE THREAD

**Issue by robsonql** [flutter/website#1589]
From URL: https://flutter.io/cookbook/forms/validation/

Why does the example use a StatefulWidget if setState is never called?

**Comment by brianegan** [comment]
Hey there -- sorry I missed this one! In this case, you need to use a StatefulWidget so you can create a unique `GlobalKey<FormState>()` exactly one time and store is as a variable that can be accessed at different points later on.

If you were to make this a StatelessWidget, you'd still need to store this key *somewhere* since you wouldn't want to recreate a new `GlobalKey` each time the `build` method is run. In this case, I store that key inside the `StatefulWidget`.
