### ISSUE TITLE
[dash] Samples catalog does not appear in the sidenav

### ISSUE THREAD

**Issue by chalin** [flutter/website#1612]
Should it be added to the **Reference** section?

Relevant links:

- flutter.io: https://flutter.io/catalog/samples/
- dash: https://flutter-io-staging-1.firebaseapp.com/docs/catalog/samples

**Comment by galeyang** [comment]
The team recently decided to take it down for now, since it's out of date and overshadows new content we've recently added in the Samples github repo. We'll figure a more comprehensive replacement of its function in the future proposal that @InMatrix will be working on.

**Comment by chalin** [comment]
Ok. In the meantime, what should I redirect [/catalog/samples/](https://flutter.io/catalog/samples/) to under the new site?

**Comment by galeyang** [comment]
> what should I redirect /catalog/samples/ to under the new site?

@RedBrogdon Do you have any suggestions?

**Comment by chalin** [comment]
Btw, while the samples are not linked to from the sidenav, the pages still exist under dash. For examples, see https://flutter-io-staging-1.firebaseapp.com/docs/catalog/samples.

Two choices come to mind:

(1) Keep the samples catalog, and link to it from the sidenav section on "Samples & codelabs", but mark the samples as "Obsolete". This is what we've done, for example, on the [dartlang.org/articles](https://www.dartlang.org/articles) index page and, e.g., this individual article page: https://www.dartlang.org/articles/language/await-async.

(2) Eliminate the sample catalog pages entirely from the site. As a redirect target for [/catalog/samples/](https://flutter.io/catalog/samples/), I could create an index page for the sidenav "Samples & codelabs" group that would simply list the nav entries of this group.

WDYT?

**Comment by InMatrix** [comment]
My preference is (1), we can even consider showing the link to the samples catalog in a lighter shade of gray and mark it as "Deprecated" or "Obsolete". In the page itself, we can state that we are working on a new visual index of UI samples and this page won't receive updates, in the mean time, please visit the Github repo and the cookbook. In addition, the link should go below the link to the samples repo on GitHub, since @RedBrogdon was concerned about showing the samples catalog will direct attention away from the samples repo, which has a lot more content. 

I'd be interested in hearing others' opinions on this.

**Comment by sfshaza2** [comment]
I like Tao's suggestion, especially if making the text in the sidenav grey is not too hard.

**Comment by sfshaza2** [comment]
Talked about this in our morning standup. Fernando is going to implement a deprecated/watermark format that we can apply to pages. Patrice will (I believe) grey the page out in the sidenav.
