### ISSUE TITLE
[dash] sidebar behavior

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#1618]
When you scroll down in the side bar, open up some categories, etc, then click on a page, the sidebar zooms (scrolls) back to the top.

This is highly jarring. Can we fix?  I feel that this is a P0, but let me know if it's too hard to fix this in time.

**Comment by fertolg** [comment]
Hey @sfshaza2, I'm with Patrice, this is basically 'unfixable' because every page is it's own html. We aren't reloading a portion of the site dynamically with javascript, we are simply linking to a different page. 

I think this behavior is quite normal though, for example, see this page: https://developers.google.com/web/fundamentals/

If you open all the options and select the one at the very bottom, you'll be taken to a page that has that bottom section open but everything else resets.

**Comment by sfshaza2** [comment]
OK, I accept that this is normal and expected. For now.  ;)
