### ISSUE TITLE
Inspector tool page is out of date

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#1621]
The inspector tool has changed since the page was written (and the fancy animated GIFs were created).

It needs to be updated.

Jacob says he can get to this after 11/1.

**Comment by parlough** [comment]
I'm going to close this as it seems the page has been essentially completely remade/updated since this issue was made in https://github.com/flutter/website/commit/7ba5437f9a30a97715c4dc0cc9d02b2098ecb793 then further updated in https://github.com/flutter/website/commit/aa0d29ddd87dca6804fd0bd57cc8f57a95bfc0ca, https://github.com/flutter/website/commit/602d16ece3507ffa72c6d5a31731fcc7d93fa625, and https://github.com/flutter/website/commit/8a0c95d412cf5e47d45ea22e15d931afacd0c43e
