### ISSUE TITLE
[dash] Clicking a link closes the site navigation

### ISSUE THREAD

**Issue by Hixie** [flutter/website#1637]
I navigated myself to the widget catalog by clicking Development. then User Interface, then Widget catalog, having looked at all the pages above it. Then I clicked a link on the page. The navigation menu closed, losing all my navigation state and confusing me about where I was.

**Comment by sfshaza2** [comment]
I agree, @Hixie. I filed a bug about this, too. But it's a side effect of the implementation. I'll let @chalin and @fertolg weigh in.

**Comment by chalin** [comment]
This is a consequence of our choice of

 1. Designing a task-based IA.
    - A corollary is that resources sometimes appear in two places, and then we need to choose one of these places as the canonical representative. This issue has been raised before: 
       _[dash] What to do with pages appearing in two places?_ #1496
 2. Implementing the site via static generation, as opposed to a Single Page App (SPA).

The specific situation that you describe for this issue seems akin to clicking on a link to an API doc page, which brings you to another context. Likewise, clicking on a widget catalog entry brings you to the widget group's doc page, which happens to live in the **Reference** section of the site. Does that not seem reasonable?

Might it help if such links were decorated with something similar to the "external link" icon that we use elsewhere, like this: <img width="101" alt="screen shot 2018-11-01 at 11 12 59" src="https://user-images.githubusercontent.com/4140793/47860548-2263db00-ddc7-11e8-9c3a-42d640d42fed.png">

While using an icon might be an interesting idea, it could also confuse readers if there are two kinds of icons.

Maybe we just need to get used to this new IA? Or maybe we need to brainstorm a bit more about this. @galeyang @InMatrix do you have any comments?

cc @fertolg

**Comment by InMatrix** [comment]
The specific case in question here is when the user is on https://flutter-io-staging-1.firebaseapp.com/docs/development/ui/widget-catalog, clicking a link such as https://flutter-io-staging-1.firebaseapp.com/docs/reference/widgets/basics will close `Development > User interface` and open `Reference`. I understand what led to this from an implementation point of view, but it's jarring from a UX perspective. 

May I suggest two ideas for the purpose of brainstorming a solution?

1. As a workaround, it might be less disruptive if a section (e.g., `Development`) won't auto collapse when a page outside of this section is opened. Since it's easy enough to collapse the top-level sections manually, doing so automatically might be more annoying than useful. Sometimes, the user might need to go frequently between two sections, such as `Reference` and `User interface'.
1. Can we have two URLs for the same page? In other words, would it be possible to have both https://flutter-io-staging-1.firebaseapp.com/docs/reference/widgets/basics and https://flutter-io-staging-1.firebaseapp.com/docs/development/ui//widgets/basics point to the Basic Widgets page? If that's possible, then we can probably use relative links in the widget catalog, so when it's opened in the `user interface` section, all links within will point to `/docs/development/ui/...` instead of `/docs/reference/...`.

**Comment by chalin** [comment]
(2) Yes we can have a page appear at two different URLs. This suggestion was previously rejected, but maybe we've reached a point where we can see that it isn't that bad an option.

(1) Given our choice of implementation for the site, (1) isn't going to be easy to implement. (Of course, it is doable, but I'm unsure that it is worth it.) IMHO, option (2) is better anyways :).

**Comment by InMatrix** [comment]
> This suggestion was previously rejected

What's the main reason against it? I'd like to understand the downside of doing this. Does it make SEO or analytics less effective?

**Comment by galeyang** [comment]
>>This suggestion was previously rejected

>What's the main reason against it? I'd like to understand the downside of doing this. Does it make SEO or analytics less effective?

I remembered at the time we were a little concerned about SEO (or analytics) but didn't go into a deeper evaluation of this.

**Comment by chalin** [comment]
@sfshaza2, had some objections earlier, but after discussing this during our standup, she is ok with (2).

Unless someone speaks up, I'll go ahead with option 2 (though possibly not before tomorrow). I suspect that we can tweak analytics appropriately as needed (to declare selected pages as aliases).
