### ISSUE TITLE
[dash] add short description before "Coming from another platform? ..." to clarify value prop

### ISSUE THREAD

**Issue by maguinis** [flutter/website#1648]
Since the first things users see are: Coming from another platform? Docs: iOS, Android, Web, React Native, Xamarin, I suggest we add this snippet of text right above it: 

"Flutter allows you to build beautiful native apps on iOS and Android from a single codebase."

If nobody goes further they still understand our value prop.

**Comment by fertolg** [comment]
@maguinis This is an easy change to make, I'll apply it, however I did want to bring up that I've never understood why the platforms callout is so high up on the page. It doesn't seem like it belongs there, it seems it's better suited in the platforms section, or in the intro to the Docs.

And the statement you added is a great Flutter description, I would advise having that in the Intro card instead of this: "Flutter is a mobile SDK for iOS and Android apps developed at Google in partnership with the global community. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source."

It seems the most important sentence on the homepage is just a sidenote as it stands right now:

![cjvzjjqfuxq](https://user-images.githubusercontent.com/2965170/47880775-606df880-dde1-11e8-88c7-659f32750f49.png)

**Comment by maguinis** [comment]
@fertolg @chalin -- I hear you, but this is intentional. Right now, the value proposition of Flutter is not evident. People can see the carousel and it takes a while to understand what Flutter actually is (and the single codebase component). 

This is a value prop but not repetitive with our sub tagline. It immediately informs about Flutter without having to scroll. If you have further questions on this one, feel free to ping. Thanks.
