### ISSUE TITLE
Maybe contextualize the word 'Reflectly' a bit more

### ISSUE THREAD

**Issue by xster** [flutter/website#1665]
In the bottom right of Expressive, beautiful UIs, it just says 'Reflectly'. 

For new visitors, it might not be clear whether it's a mobile app built on Flutter or just a one word statement. 

Maybe surround with 'Showcase' or 'App' or their icon or something.

**Comment by sfshaza2** [comment]
An interesting point. So it would say either "Reflectly App" or similar.

@maguinis, what do you think?

**Comment by maguinis** [comment]
Good point. It made more sense with the static image but with the GIF we should adjust. 

How about we add the iOS frame, too (given that is a focus for them) with the same GIF and underneath both phones we state:

"Reflectly App built with Flutter and featured in App Store 
Download: iOS, Android
Learn more"

**Comment by xster** [comment]
Sounds good. The "built with Flutter and featured in the App Store" can use a different typography too to not be too crowded.

**Comment by sfshaza2** [comment]
Is this still an issue, @xster? The home page says: "Reflectly. An award winning mindfulness app built with Flutter." And it has links to both the iOS and Android downloads. Seems pretty clear.

The showcase page seems equally clear. This bug was filed before Flutter Live, so I'm not sure it's still valid.

**Comment by xster** [comment]
LG now
