### ISSUE TITLE
'Inside Flutter' page issue

### ISSUE THREAD

**Issue by Rahiche** [flutter/website#1676]
Page URL: https://flutter.io/docs/resources/inside-flutter.html
Page source: https://github.com/flutter/website/tree/dash/src/docs/resources/inside-flutter.md

in Inside Flutter page  i see this 

Notice that the **_child’s_** layout cannot depend on the **_child’s_** position because the **_child’s_** position is not determined until after the child returns from layout

i am not an English expert but maybe this can be delivered better ?

**Comment by Purukitto** [comment]
1. `Note that the child's layout cannot depend on its position, as the position is described by the parent only after it returns from the layout.`
  Rephrased the sentence to be grammatically correct, understandable and proper use of pronouns and voice. Should be fine as the page had several blocks of text following similar layout.

2. `Note that the child's layout cannot depend on the child's position, as the position is described by the child's parent only after it returns from the layout.`
  Similar to the above but kept the nouns instead of using pronoun's, might result in being more legible in some case. Is still grammatically correct.

**Comment by Purukitto** [comment]
I have gone ahead and made a pull request using the first option

**Comment by Rahiche** [comment]
I guess this should be closed now
