### ISSUE TITLE
Flutter wordmark is badly aliased in Firefox

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#1755]
Using Firefox 63.0.3 64-bit on Linux, the Flutter wordmark on the redesigned Flutter website is badly aliased (i.e. jagged) and looks terrible:

![flutter_wordmark](https://user-images.githubusercontent.com/17391434/48791808-76b3f980-eca7-11e8-98e7-01448a4cf10e.png)

It looks fine with Chrome 70.0.3538.110 (Official Build) (64-bit) on the same system.

~~It seems that Firefox doesn't antialias SVG text by default.~~

**Comment by kisaragi-hiu** [comment]
This is caused by #2601. (I'm the person who complained on Twitter.)

Below are the [logo](https://github.com/flutter/website/blob/master/src/_assets/image/flutter-lockup.svg) ([permalink](https://github.com/flutter/website/blob/d3dd4af648534dbd1dc95d6faff2af90c5be41b7/src/_assets/image/flutter-lockup.svg)), the PNG extracted from it, and an SVG with text. Only the png-within-svg is not being anti-aliased.

![Screenshot_20190420_142101](https://user-images.githubusercontent.com/11722318/56453606-8b400f00-6377-11e9-9bc5-5b5158385b1f.png)

**Comment by jamesderlin** [comment]
Closing in favor of #2601.
