### ISSUE TITLE
Update 'Building Layouts' page to current best practices

### ISSUE THREAD

**Issue by feinstein** [flutter/website#1799]
Page URL: https://docs.flutter.dev/ui/layout
Page source: https://github.com/flutter/website/tree/master/src/docs/ui/layout/index.md

Description:

The first part of this page shows how to build a layout. Although it's not incorrect, I don't think it's built as a reference should be. 

First it uses `Container` all the time, as explained in the text, for adding padding. I think the `Padding` Widget should be mentioned, and also the `SizedBox` Widget should be pointed out as an option as well to space the widgets, since it avoids nesting of widgets in `Row` and `Column`.

Also, there's a `Scaffold` adding a title that's not on the original reference image.

**Comment by sfshaza2** [comment]
Interesting. This advice should be revisited (it was first written long before 1.0).

**Comment by micpap25** [comment]
After review of the page, it looks like a lot has been changed since this issue was made. 
The first issue still stands: the page has no reference to `Padding` and heavily encourages the use of `Container` for padding. 
The second issue is also present, and the guide specifically recommends nesting with rows and columns. Mention to `SizedBox` exists but only in passing to explain how to constrain a card. 
The third issue looks fixed to me, the section on `Scaffold` seems completely unrelated to the reference image. 

I guess the question is @Sfshaza , how sweeping do you want this revision to be? Should the site just mention all the things brought up in the issue, or should new sections be created and / or old sections be removed?

**Comment by atsansone** [comment]
@Hixie : Would you have advice as to which best practices we should consider when revising this page?

**Comment by goderbauer** [comment]
Happy to provide input to such a review. Also, the points raised so far on this issue all look valid.

**Comment by parlough** [comment]
We've discussed reorganizing and rewriting some of the layout documentation (and related tutorials), so I love the idea of starting with collecting a review of this doc and other best practices.

**Comment by parlough** [comment]
Reopening since the change was reverted in https://github.com/flutter/website/pull/9927
