### ISSUE TITLE
'Return data from a screen' page issue

### ISSUE THREAD

**Issue by Simpler1** [flutter/website#1887]
Page URL: https://flutter.io/docs/cookbook/navigation/returning-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/returning-data.md

Description:
Click "Pick an option...", then click "Yep!".  Notice that "Yep!" appears in the snackbar.
Then click "Pick an option..." , then click "Nope.".  Notice that that "Yep!" appears in the snackbar.
The correct value is returned from pop, but the UI doesn't get updated.  I think this is because it is a stateless widget.  There should probably be a stateful widget and setState() should be called to update the displayed value of result.

**Comment by chalin** [comment]
Thanks for the issue. I'll let @brianegan comment.

**Comment by brianegan** [comment]
Hey there -- thanks for writing in! 

  > I think this is because it is a stateless widget. There should probably be a stateful widget and setState() should be called to update the displayed value of result.

Every time the user selects an Option, the code queues up a new Snackbar. By default, each snackbar will be shown for 4 seconds, then hide. If you quickly select "Yep" then "Nope," and wait a few seconds, you should see both the "Yep" Snackbar and the "nope" Snackbars appear.

Since this is the default behavior of Snackbars, I didn't consider it a bug, but I can definitely understand why it seems like one! 

I'll push up a PR that reduces the Duration each Snackbar is shown, so if you select one option after the next rapidly each Snackbar will appear more quickly.

**Comment by Simpler1** [comment]
@brianegan Thanks for the explanation Brian.  That is exactly what was happening.  Since the snackbar was not visible on the second screen, I thought that it was displaying the first selection "again", but in fact it was "still" showing the first selection after picking the second selection.  Is there a way to cancel the snackbar after the user presses a button?  That seems like the best user experience.

Thanks again.  You can close this issue.

**Comment by Simpler1** [comment]
It's as simple as adding the following line immediately above the current showSnackBar line:

    Scaffold.of(context).removeCurrentSnackBar();

Then you don't need to limit the time that the snackbar is displayed.

**Comment by brianegan** [comment]
@Simpler1 You're right, that's a better solution! I've posted a PR with that fix in place.

Thanks again for raising the issue and helping craft a solution :)
