### ISSUE TITLE
Can't search docs.flutter.io from a mobile browser

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2071]
@eseidelGoogle commented on [Mon Jul 30 2018](https://github.com/flutter/flutter/issues/19988)

At least in Chrome on iOS (and presumably other mobile browsers) there is no search box on docs.flutter.io.

@mjohnsullivan @jcollins-g 

---

@jcollins-g commented on [Mon Jul 30 2018](https://github.com/flutter/flutter/issues/19988#issuecomment-408920969)

dart-lang/dartdoc#1348

---

@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter/issues/19988#issuecomment-444871868)

Same problem in https://flutter.io and https://docs.flutter.io

**Comment by chalin** [comment]
> At least in Chrome on iOS (and presumably other mobile browsers) there is no search box on docs.flutter.io.

There is if you browse in landscape view. Is that good enough for now @eseidelGoogle @mattrenquist et all?

---

> Same problem in https://flutter.io

For flutter.io, the search box is under the hamburger:

<img width="680" alt="screen shot 2018-12-17 at 10 42 44" src="https://user-images.githubusercontent.com/4140793/50097742-87915580-01e8-11e9-804a-2d654c5e3ab3.png">

cc @kwalrath @sfshaza2

**Comment by zoechi** [comment]
Discoverability is not great though.

**Comment by chalin** [comment]
@InMatrix @galeyang - thoughts?

**Comment by galeyang** [comment]
I agree that the discoverability is not great. If we would like to move it to the header, we need to rearrange the existing header items due to the limited space. For example, other frameworks created a minimized version of logo (e.g. Angular and React use an icon-only version, Firebase uses a text-only version) or hide those icons for social media (i.e. Twitter and Youtube icons).

For the usage, in the past month, only a few unique searches were from mobile devices. I guess it's partly because of the low discoverability and the fact that most programming activities are on desktop. Therefore, if we have future plans on improving general search features on the website (e.g. auto-suggestion, search results), I'm also fine with making changes later and working on high priority issues first.

**Comment by sfshaza2** [comment]
- Do you mean that you can't search docs.flutter.io from flutter.io?
- The search text field is under the hamburger menu on flutter.io. Is this acceptable?

I guess I'd like to close this bug, unless we deem that the search needs to be directly on the mobile front page.

@eseidelGoogle @galeyang

**Comment by eseidelGoogle** [comment]
I'm not sure how I search on docs.flutter.io:

![image](https://user-images.githubusercontent.com/11857803/51945335-4d17fc80-23d3-11e9-89b6-31c479fbe491.png)

**Comment by eseidelGoogle** [comment]
I suspect this is a dartdoc bug more than a flutter/website bug?

**Comment by sfshaza2** [comment]
There is a search textfield on docs.flutter.io. It is suboptimal in my opinion, though. It seems to be on every page, so that's a good thing. But it forces code completion and it doesn't even look at the docs for Java and ObjectiveC. Those packages are almost undiscoverable.

<img width="657" alt="screen shot 2019-01-29 at 2 46 41 pm" src="https://user-images.githubusercontent.com/44418985/51945916-e09dfd00-23d4-11e9-97bd-11190944f44a.png">

Finally, bugs against the docs should be filed against the flutter/flutter repo (if content based) or the dartdoc repo (if tool based), rather than the website repo.

**Comment by sfshaza2** [comment]
Oops, oops, oops! You are completely right that it's impossible to search the Flutter API docs from a mobile device. But this bug should be filed against dartdoc. I will open a bug there, and close this one.

**Comment by sfshaza2** [comment]
Opened a bug against dartdoc:
https://github.com/dart-lang/dartdoc/issues/1914
