### ISSUE TITLE
'Testing Flutter apps' page issue

### ISSUE THREAD

**Issue by AJ9** [flutter/website#2165]
Page URL: https://flutter.io/docs/testing/
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/index.md

Description:

The unit testing documentation currently specified contains an incorrect package import: 

Current full example:

```
import 'package:test/test.dart';

void main() {
  test('my first unit test', () {
    var answer = 42;
    expect(answer, 42);
  });
}
```

Where `import 'package:test/test.dart';` should be `import 'package:flutter_test/flutter_test.dart';`

**Comment by chalin** [comment]
Thanks for this issue. There is indeed a problem with the sample code given in the Unit Testing section, but as I commented in #2166, I believe that the intent was to illustrate direct use of the test package. cc @brianegan, @sfshaza2

**Comment by sfshaza2** [comment]
That is also my understanding.

**Comment by brianegan** [comment]
Hey all -- that is correct! In fact, I need to review the cookbook recipes to see if they suffer from this same problem.

It looks like #2168 solves this problem in the correct way. 

Maybe should open a separate issue, but I'm wondering: Should we actually trim down this testing page a bit in general and link more to the cookbook? The page could describe the testing offered by flutter and the philosophy, but the examples would just link to recipes instead?

Overall, I'd written a lot of the content in the cookbook as a more in-depth replacement for this page, since I'd found it lacking in content when I first tried to use it myself a while back.

**Comment by chalin** [comment]
> Should we actually trim down this testing page a bit in general and link more to the cookbook? The page could describe the testing offered by flutter and the philosophy, but the examples would just link to recipes instead?

I agree. I've opened #2178 to track this.

**Comment by AJ9** [comment]
@brianegan just seen the cookbook. There is a lot there already which seems like a good place to consolidate! Shall I close this issue?

**Comment by sfshaza2** [comment]
@brianegan, I'm ok with trimming the testing page, and linking to the cookbook where things are consolidated.

**Comment by mjohnsullivan** [comment]
Changes in https://github.com/flutter/website/pull/2330

**Comment by micpap25** [comment]
It looks like this issue an all its follow-ups have been resolved, I think this can be closed.

**Comment by sfshaza2** [comment]
Thanks! Closing.
