### ISSUE TITLE
Every Web page should have an edit button

### ISSUE THREAD

**Issue by Hixie** [flutter/website#2182]
...that sends you straight to the relevant page on GitHub.

(From https://github.com/flutter/flutter/issues/10416)

**Comment by chalin** [comment]
We have such a button that links to the GitHub page source, like this:

> <img width="594" alt="screen shot 2019-01-08 at 19 45 44" src="https://user-images.githubusercontent.com/4140793/50868558-16276b80-137e-11e9-8ffb-79bd01c1bc5b.png">

The button title is "View page source" because that is what the link leads to: the page source on GH. And on that page, the user will find an edit button. (If the user hasn't forked, I believe that she/he will be asked if they want to fork ... or maybe it automatically forks, I can't recall for sure).

cc @sfshaza2 @kwalrath

**Comment by sfshaza2** [comment]
Closing, please reopen if you still feel it's an issue.
