### ISSUE TITLE
Codelab mixes assumptions of context between terminal and IDE

### ISSUE THREAD

**Issue by xster** [flutter/website#2278]
The codelab goes back and forth between assuming the user is in an IDE and terminal.

For instance, it starts with 

```If you don’t see “New Flutter Project” as an option in your IDE, make sure you have the plugins installed for Flutter and Dart.```

and

```Run the app by clicking the green arrow in the IDE.```

but then goes into

![screen shot 2019-01-25 at 10 45 14 am](https://user-images.githubusercontent.com/156888/51766026-567d2e00-208e-11e9-921e-aae80cd22af3.png)

which only makes sense when running in a terminal.

**Comment by chalin** [comment]
While the [Test drive](https://flutter.io/docs/get-started/test-drive) supports Android Studio, VS Code and use of the terminal, I'm not sure I want to do the same thing for any page beyond that, including the codelab.

A simple solution to this issue is to remove the comment, or make it clear that it only applies to folks working from a terminal. I'd be in favor of simply dropping the tip.

@sfshaza2 - any comments about this? /cc @filiph

**Comment by xster** [comment]
There's also a hot restart button in intellij/AS

**Comment by sfshaza2** [comment]
It may be that I'm being forgetful, but I'd suggest leaving the tip but removing the text of the warning, or summarizing it (ie. not verbatim).

**Comment by sfshaza2** [comment]
I removed the verbatim note and summarized it. Fixed.
