### ISSUE TITLE
Reduce doubles to ints

### ISSUE THREAD

**Issue by xster** [flutter/website#2279]
Since Dart 2.1 supports double-to-ints.

For instance ` final _biggerFont = const TextStyle(fontSize: 18.0);` could be `final _biggerFont = const TextStyle(fontSize: 18);`

etc

**Comment by chalin** [comment]
@Hixie @filiph @gspencergoog, any comment about this? /cc @sfshaza2

**Comment by chalin** [comment]
@sfshaza2 @filiph et all: note that

1. I've applied this change to all example apps under the `examples` folder.
1. We **can't just do a global search-and-replace** for code snippets that are unchecked (those with `<-- skip -->` before them). There are situations where type inference is at play and using `int` arguments might require adding a `<double>` type argument.

Here is a concrete example of 2 that I encountered:

- Original code: `Tween(begin: 0.0, end: 300.0)`

- Just dropping `.0` leads to a type error:
  `Tween(begin: 0, end: 300)` --> is inferred as a `Tween<int>`, which is ok, but it wasn't what was expected in the context that the change was made.

- Fix (add `<double>` type argument): `Tween<double>(begin: 0, end: 300)`

**Comment by atsansone** [comment]
@gspencergoog : What exactly would we need to do to resolve this issue? The request is vague. Thanks!

**Comment by gspencergoog** [comment]
If the example code has the `.0` removed from most of the double args, I think this is resolved.  The places where a type would have to be added because the compiler can't infer the correct type (like the `Tween` example above), I think it's fine to just leave the `.0`, as that is enough to infer the right type and still is pretty readable. Although it might help with comprehension in some cases to be explicit about the types, adding `<double>` could also be too verbose for some short examples, so I'd probably just leave those to case by case judgement.
