### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/website#2443]
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
there is issue in case using sqlLite to save data, data is getting lost in case getting update for same app from google play, only its working fine in case iam doing backup for the app via google account then doing update data is retained.

**Comment by brianegan** [comment]
Hey there! The `getDatabasePath` from the `sqflite` library returns the `databases` directory for your Android app. That directory should not be wiped out when upgrading, and the data should still be there.

Since we're using the official method from the library, I wonder if this might be an issue with the `sqflite` library itself, or if some other funny business is going on.

To help out, I've opened an issue on the `sqflite` side as well to see if the author might have some more information! 

https://github.com/tekartik/sqflite/issues/166

**Comment by alextekartik** [comment]
Hi @kw2019ltd do you mind following this issue here https://github.com/tekartik/sqflite/issues/166 instead and describe:

* your database location path
* whether the database has the same version/schema/code before and after the update
* whether it was tested using the release version the app (i.e. same application id and signature)
* how I could reproduce the issue

thanks!

**Comment by brianegan** [comment]
Thanks so much for the help, @alextekartik! I'll keep this issue open for now and track the progress on the sqflite side. If we find something that will be helpful to document, I'll update the recipe!

**Comment by brianegan** [comment]
Closing this down for now since we haven't heard from the user since the initial report. @kw2019ltd, please feel free to reopen if you discover an issue with the recipe :)
