### ISSUE TITLE
Can't get Nesting Rows and Columns on 'Layouts in Flutter' page to work

### ISSUE THREAD

**Issue by mkwsra** [flutter/website#2459]
Page URL: https://docs.flutter.dev/ui/layout
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

When I tried to apply the example everything went as expected until I tried to apply [Nesting rows and columns](https://docs.flutter.dev/ui/layout#nesting-rows-and-columns)

It seems there are problems with the logic, the compiler is complaining about not being able to use the variable "stars" to be more specific:
_only static members can be accessed in initializers_

And the problem persisted with other variables till I reached [Common layout widgets](https://flutter.dev/docs/development/ui/layout#common-layout-widgets)

**Comment by JosephineAkello** [comment]
@mkwsra did you place the titleSection widget at the top of the build widget, just after the build context function as stated in the tutorial?
as 
```
Widget build(context) {
    Widget titleSection = Container( //rest of the code)
}}
```
 since the error you are getting of **only static members can be accessed in initializers** means that theres no way the variable is accessed at that point since initializers are executed before the constructor
