### ISSUE TITLE
Building a form with validation - Requiring GlobalKey

### ISSUE THREAD

**Issue by Piinks** [flutter/website#2479]
In [cookbook/forms/building a form with validation](https://flutter.dev/docs/cookbook/forms/validation),
Step 1 explains the use of the GlobalKey with a Form as required. It caused a bit of confusion when working on samples for API Docs ([see PR for API Docs here](https://github.com/flutter/flutter/pull/28857)), as the validation shown in this example can also be achieved through the use of the `Forms.of()` method.

Using a GlobalKey with Forms has been explained to me as a preferred method, but not necessarily required.
I wasn't sure if we could  explain this better by just changing the wording in the cookbook, or going further and changing the sample code as well.

Thoughts? 🙃

**Comment by brianegan** [comment]
Hey, thanks for writing in! I'm the author of the cookbook and happy to make the change, but I'm not 100% sure on which method is preferred and which one we should guide users toward.

My quick thoughts: I feel like it's best to focus on the preferred method and provide links to the docs for the alternative method. Overall, I like to keep recipes focused on the task at hand so folks can jump in and out for answers instead of providing too many options and requiring the user to evaluate and decide on the appropriate path.

Therefore, @Sfshaza can you help us find the right Flutter team member that can answer the question: Which is the preferred method for accessing the form: Form.of or GlobalKeys?

Thanks again!

**Comment by sfshaza2** [comment]
@Hixie, it looks like you might own this? Can you advise on whether Form.of or GlobalKeys is preferred?

I agree, @brianegan, that we don't want to confuse our users. Document the preferred method and maybe, if it makes sense, mention the other.

**Comment by sfshaza2** [comment]
I got this straight from a Flutter engineer:

I believe we reached a consensus on this! GlobalKeys preferred, but not required. In the cookbook sample for form validation, Form.of would work because it returns the closest FormState that encloses the given context, and the validation is taking place within that scope. Outside of that scope though, Form.of may not return the state you are expecting.

**Comment by brianegan** [comment]
Thanks Shams, that's helpful. Based on that feedback, do you all think we should make any changes to the recipe since we're documenting the preferred method already?

**Comment by sfshaza2** [comment]
I wonder if it makes sense to add a note.  something like "If you're aren't sure whether to use Forms.of or GlobalKey for Form validation, GlobalKeys is preferred. In this eample, Form would work because it returns the closest ..."

I think the fact that it may not return the state you expect might be worth noting. Thoughts?

**Comment by brianegan** [comment]
PR with changes here: #2517.
