### ISSUE TITLE
please help us to migrate from flutter-es.io to flutter-es.dev

### ISSUE THREAD

**Issue by Twinber** [flutter/website#2489]
I would need advice on migration to .dev domain for flutter-es.io, without affecting SEO.
How have you done the redirections, so that each url of the old domain, leads to the corresponding url of the new one?

**Comment by kwalrath** [comment]
@mit-mit can you tell us what the magic is?

**Comment by sfshaza2** [comment]
@Twinber, let me see if I can find someone to help you.

**Comment by kf6gpe** [comment]
Hi! This repo may help you with forwarding --- we used this for a few days with manual redirect rules in Firebase to redirect to our new URLs. 

[old-website-io-redirect](https://github.com/flutter/old-website-io-redirect)

**Comment by sfshaza2** [comment]
@Twinber, @kf6gpe was responsible for redirecting to the new domain. With your request, we've made the redirect repo public. I'm glad you asked!

**Comment by filiph** [comment]
More generally, you want to HTTP 301 redirect each URL from one site to another. HTTP 301 tells the search engines this is a permanent move. You can also log onto the search engine's console (like [Google Search Console](https://search.google.com/search-console/about)) and follow instructions there.

For specific redirect rules, and more specifically for Firebase Hosting redirect rules, look at https://github.com/flutter/old-website-io-redirect/blob/master/firebase.json#L9. We had to do the `/:a/:b/:c*` thing because Firebase doesn't allow wildcards spanning across slashes.

**Comment by Twinber** [comment]
Thank you very much for the information, you are great.

**Comment by sfshaza2** [comment]
@Twinber, can I close this?

**Comment by Twinber** [comment]
Yes @sfshaza2, Thanks again
