### ISSUE TITLE
Offer another way to create `TextEditingController` on 'Handle changes to a text field' page

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2523]
Page URL: https://docs.flutter.dev/cookbook/forms/text-field-changes
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/text-field-changes.md

Description of issue:

Is it there any reasons for creating the `TextEditingController` as a `State` `field`:

```dart
class _MyCustomFormState extends State<MyCustomForm> {
  // Create a text controller. We will use it to retrieve the current value
  // of the TextField!
  final myController = TextEditingController();
```

Instead of creating it, and listening, at `initState()`?

```dart
TextEditingController myController;

@override
  void initState() {
    super.initState();

    myController = TextEditingController()..addListener(_printLatestValue);
  }
```

I am not sure how `createState()` and `initState()` relate to each other (I think `createState` always calls `initState` eventually, since we create a new `State` to place it into a tree, and `initState` is called when a `State` is first attached to a tree), I just want to understand pros and cons of this way of initialization, to learn on how to balance them (or if there's no difference at all, just one is `final` and the other is not), or if there are any issues in creating and listening to the `TextEditingController` as a class field, instead of at `initState`.

I might be nitpicking, and maybe this is more a question than an issue, but the Flutter lifecycle and performance is still not very much documented so it's hard to balance what can have side effects and what not.

**Comment by feinstein** [comment]
For example, the [Focus cookbook](https://flutter.dev/docs/cookbook/forms/focus) says:

> Since focus nodes are long-lived objects, we need to manage the lifecycle using a `State` class. To do so, create the `FocusNode` instance inside the `initState` method of a `State` class, and clean them up inside the dispose method.

So is it ok to initialize a `FocusNode` on the field declaration? Or should the `TextEditingController` creation be moved to the`initState` method? And why?

**Comment by brianegan** [comment]
Hey there! Thanks for writing in.

In general, instantiating the field in `initState` vs when the state object is first constructed should not result in much of a difference: The field will be instantiated slightly later if you do it in `initState`. 

Performing instantiation in `initState` can be handy if you need to use values passed to the Widget, or if you need to access the current state object. Since neither of those are true, I saved a few lines of code by directly instantiating the Controller when the State class is instantiated.

So, that explanation aside: I'd like to make this as easy as possible for folks! What do you think should be demonstrated here? Should we be consistent and always instantiate objects in `initState`?

Overall, the goal of the cookbook is to offer very direct solutions that do not cause folks too many headaches like this, although it's natural they come up :) Therefore, I'm happy to make any changes you feel would clarify this topic for end users without getting too far into the weeds!

**Comment by feinstein** [comment]
Well, I like the idea of showing many different ways of doing the same things, this promotes flexibility and, to some, curiosity.

The best solution IMO is to have another recipe explaining the pros and cons of everything you guys show differently here and there. So in this case, there could be a note with the link for the recipe on "differences between variable initialization - field or initState?" or something like it.

This way we can get the best of both worlds :)

**Comment by sfshaza2** [comment]
@miquelbeltran, please review

**Comment by miquelbeltran** [comment]
I don't think we should encourage devs to initialize variables this way if it is not strictly necessary, because it adds complexity to the code with the use of `late` init, the `..` (cascade operator), and having to specify the type of the `myController` variable.

```dart
late final TextEditingController myController;

@override
  void initState() {
    super.initState();

    myController = TextEditingController()..addListener(_printLatestValue);
  }
```

The way the recipe (https://docs.flutter.dev/cookbook/forms/text-field-changes) is currently doing it seems cleaner to me:

```dart
class _MyCustomFormState extends State<MyCustomForm> {
  final myController = TextEditingController();

  @override
  void initState() {
    super.initState();

    myController.addListener(_printLatestValue);
  }
```

**Comment by feinstein** [comment]
When I opened this issue 4 years ago the  `late` keyword didn't exist.

My point at the time was to understand when to initialize something at `initState` and when to initialize as a variable of the `State` class.

The `TextController` cookbook at the time had patterns that conflicted with the `Focus` cookbook's recommendation. My point was more to keep consitent examples, or to explain why they differ, as this is education material after all.

I am not asking for the code example to change to worse code, but for an explanation to be added to justifiy the deviation from a recommendation from another cookbook.

**Comment by feinstein** [comment]
It's OK, back then we didn't have much information and the patterns were being born, but nowadays it's different, thanks for the attention folks.
