### ISSUE TITLE
Clarify which approach should be used Internationalization page is confusing with mention of two approaches

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/website#2611]
At the beginning of the [Internationalization page](https://flutter.dev/docs/development/accessibility-and-localization/internationalization), in the Sample internationalized apps box, a brief description and links are provided to two ways of handling i18n in apps: a simple example, and a more sophisticated one using the Dart intl package.

After this box, the text begins to describe the flutter_localizations package without reference to the simple/intl ways of doing things, and it is confusing as to which approach this is, and there's no mention of simple again in the text from there on.

**Comment by HansMuller** [comment]
This section returns to the Dart intl package example: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#defining-a-class-for-the-apps-localized-resources

This section (two sections later) returns to the minimal rough-and-ready i18n example: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#an-alternative-class-for-the-apps-localized-resources

Both examples appear at the outset only because I assumed that many developers wouldn't want to read through the tutorial; they'd prefer to skip directly to a complete example.

I agree that the headings and text could be clearer about overall structure of the tutorial.

**Comment by sfshaza2** [comment]
This page needs reorg. See https://github.com/flutter/website/issues/3028

**Comment by sfshaza2** [comment]
Also see: https://github.com/flutter/website/issues/2885

**Comment by HansMuller** [comment]
Not to disagree, but. I'm working on a 3rd approach: https://github.com/flutter/flutter/issues/41437. The 3rd approach would be much simpler for app developers.

**Comment by atsansone** [comment]
@HansMuller : Has your 3rd approach (from https://github.com/flutter/flutter/issues/41437) been implemented? If not, do we have another option that could be documented to close this issue?

See also: https://github.com/flutter/website/issues/2885, https://github.com/flutter/website/issues/4895

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/4895. Closing this issue.
