### ISSUE TITLE
Layout issues on widgets catalog on phones

### ISSUE THREAD

**Issue by xster** [flutter/website#2625]
- There's too much horizontal margin around the column
- It would be nice to be able to specify where the word breaks happen when there indeed to little space (but I'm not a web person to know what the right solution is :()

![Screenshot_20190501_131633_com android chrome](https://user-images.githubusercontent.com/156888/57040261-b34f2e00-6c13-11e9-96fb-e27cda802454.jpg)
![Screenshot_20190501_131703_com android chrome](https://user-images.githubusercontent.com/156888/57040264-b518f180-6c13-11e9-9d59-2c9e610f8d7e.jpg)

**Comment by parlough** [comment]
Thanks for the issue! I'm going to close this in favor of https://github.com/flutter/website/issues/2313 which discusses reducing the margin on mobile. 

As for the line breakage, we already can specify a [word break opportunity](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) if it makes sense. However it may not be ideal to do so, as the breakage at the end of the line indicates clear it is part of the same type name, rather than two types or words.
