### ISSUE TITLE
'Install' page issue

### ISSUE THREAD

**Issue by EdisonTKPcom** [flutter/website#2659]
Page URL: https://flutter.dev/docs/get-started/install/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

Description of issue:
From VS Code MacOS
Flutter: New Web Project
Stagehand needs to be updated with 'pub global activate stagehand' to use this feature.
Command 'Flutter: New Web Project' resulted in an error.

**Comment by JosephineAkello** [comment]
@EdisonTKPcom  what did the error stated exactly?  Because when you create a new project, using uppercase to name a project always results to an error, package names should always be in lowercase and maybe underscores to seperate words more than one.Always make sure to use valid is  Dart identifiers -- that doesn't start with digits and are not  reserved words.

**Comment by sfshaza2** [comment]
Great question, @JosephineAkello!

**Comment by sfshaza2** [comment]
Closed due to lack of info.
