### ISSUE TITLE
Clarify how fonts are added on 'Export fonts from a package' page

### ISSUE THREAD

**Issue by awhitford** [flutter/website#2709]
Page URL: https://docs.flutter.dev/cookbook/design/package-fonts
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/package-fonts.md

Description of issue:

The instructions indicate that you also need to update `TextStyle` to reference the `package` on where the font is located.  This seems illogical when you are already being explicit in the `pubspec.yaml` file, but I just tried it and it was not necessary.  Are these instructions out of date?

**Comment by brianegan** [comment]
Hey there -- there used to be a bit of a moving target when it came to exporting fonts from packages. I'll double-check which part is still needed!

**Comment by brianegan** [comment]
Ok, so there are now 2 ways to make this work. I'd love some input on which one you all think should be documented!

  1. Declare the font in the `pubspec.yaml` and use it without the `package` property on `TextStyle`.
  2. DO NOT declare the font in the `pubspec.yaml`, and provide the `package` to the `TextStyle` 

These both achieve the same effect these days. I'm inclined to say the first option is "safer" since it does not require the consumer to know where the fonts are stored / if they move / etc, but they're functionally equivalent. @Sfshaza Do you happen to know who we could contact to help us decide which option to document?

**Comment by awhitford** [comment]
I'd expect option 1 would be the norm.  However, if option 2 also works, shouldn't that be documented as well?

I'm puzzled why the consumer needs to specify the fonts from the package in its `pubspec.yaml` rather than it be implicit from the package dependency.  See [Use the font](https://flutter.dev/docs/cookbook/design/package-fonts#3-use-the-font).

**Comment by atsansone** [comment]
The current page removed the need for declaring the package on `TextStyle`. Closing this issue.
