### ISSUE TITLE
'Cookbook' page issue : Please Update Cookbook because it's very easy to learn

### ISSUE THREAD

**Issue by MPVIRANIDEVELOPER** [flutter/website#2766]
Page URL: https://flutter.dev/docs/cookbook/
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/index.md

Description of issue: as we know the grand mobile ui flutter sdk  is spread in the world very efficiently so for that congratulation to google and also thanks for building these technology, my problem is when we go threw official docs which some time hard but using cookbook explanation we can learn easily so my request to flutter team is please update as soon as possible because many developers are waiting for these. waiting for flutter team action thank you in advance

**Comment by sfshaza2** [comment]
Thanks for this feedback, @MPVIRANIDEVELOPER. Can you provide examples of specific pages that aren't up to date?

**Comment by MPVIRANIDEVELOPER** [comment]
in animation topic, but if you implement all widget use than it will be
awesome and we don't need to refer any other data this is it.

**Comment by sfshaza2** [comment]
Hi, @MPVIRANIDEVELOPER. Thanks for this feedback. I have a writer working on updating the animation docs, and I've asked him to also take a look at the docs in the cookbook. Hey may not be able to get to it for awhile.

**Comment by MPVIRANIDEVELOPER** [comment]
ok thanks

**Comment by sfshaza2** [comment]
Actually, A DPE just started working on expanding the animations section.  :)  If you have specific requests, please list them here.

**Comment by MPVIRANIDEVELOPER** [comment]
no specific request, but we wish that if whole documentation of currently
available widgets is available than it was very very very awesome so i have
requested material update otherwise you guys are awesome thank you..

**Comment by sfshaza2** [comment]
OK, @MPVIRANIDEVELOPER, thanks for the feedback. I’m going to close this bug, because there isn’t really anything specific we can take action on. I don’t know if you ever have seen that we run developer surveys on a regular basis, to gather information on what aspects of Flutter and Flutter’s documentation that folks like, don’t like, or want more information on. That is an excellent place to give feedback like this. When we have an active survey, we put a banner on top of the website, with links. Thanks again!
