### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by nitingupta910** [flutter/website#2847]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Description of issue:

The 'Complete Example' shows how to display `CircularProgressIndicator` while `Post` is being fetched. I think this example is misleading since `fetchPost` is a synchronous call due to use of `await` for the http get request. Thus, by the time `build` is called, the post would have been already fetched.

**Comment by MaikuB** [comment]
> I think this example is misleading since fetchPost is a synchronous call due to use of await for the http get request

Actually, the use of `await` doesn't make it synchronous. Execution is synchronous until `await`. The app can do other things when it hits that point. This is what enables concurrency so that the app is free to do other stuff and thus leading a more responsive that won't block on doing long running operations.

There's an explanation on Futures [here](https://dart.dev/tutorials/language/futures) with an example that also shows the execution order. If you want to verify this behaviour, the example in that cookbook could be modified to fetch data after an amount of time. Below I've made it fetch data after 30 seconds

```
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

Future<Post> fetchPost() async {
  return await Future.delayed(Duration(seconds: 30), () async {
  final response =
      await http.get('https://jsonplaceholder.typicode.com/posts/1');

  if (response.statusCode == 200) {
    // If the call to the server was successful, parse the JSON.
    return Post.fromJson(json.decode(response.body));
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load post');
  }
  });
}

class Post {
  final int userId;
  final int id;
  final String title;
  final String body;

  Post({this.userId, this.id, this.title, this.body});

  factory Post.fromJson(Map<String, dynamic> json) {
    return Post(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      body: json['body'],
    );
  }
}

void main() => runApp(MyApp(post: fetchPost()));

class MyApp extends StatelessWidget {
  final Future<Post> post;

  MyApp({Key key, this.post}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data Example'),
        ),
        body: Center(
          child: FutureBuilder<Post>(
            future: post,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Text(snapshot.data.title);
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }

              // By default, show a loading spinner.
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
```
If you run it, you should see that it's not actually synchronous as you've thought. As if it were, then you won't see the progress indicator that will be visible for 30 seconds or so

**Comment by nitingupta910** [comment]
Thanks for the explanation. I got confused regarding what context `await` would block. The documentation you linked makes that clear.

btw, the DartPad thing is broken on: https://dart.dev/tutorials/language/futures
