### ISSUE TITLE
Correct `main.dart` example code on 'Add State Management' step in Cupertino Codelab

### ISSUE THREAD

**Issue by LloydNicholson** [flutter/website#2884]
On page: <a href="https://codelabs.developers.google.com/codelabs/flutter-cupertino/#4">Cupertino App - Add State Management</a>

The issue relates to the main.dart code displayed on the webpage at the bottom code snippet.

It doesn't match the main.dart file located here: <a href="https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-01/lib/main.dart">GitHub main.dart page</a>

The code on the webpage is wrong and GitHub page is correct.

**Comment by atsansone** [comment]
@domesticmouse : The variance between the two files appears to be:

### Codelab

```dart
import 'package:flutter/cupertino.dart';
import 'package:provider/provider.dart';             // NEW

import 'app.dart';
import 'model/app_state_model.dart';                 // NEW

void main() {
 return runApp(
   ChangeNotifierProvider<AppStateModel>(            // NEW
     create: (_) => AppStateModel()..loadProducts(), // NEW
     child: const CupertinoStoreApp(),               // NEW
   ),
 );
}
```

### GitHub

```dart
import 'package:flutter/cupertino.dart';
import 'package:provider/provider.dart';

import 'app.dart';
import 'model/app_state_model.dart';

void main() {
  return runApp(
    ChangeNotifierProvider<AppStateModel>(
      create: (context) => AppStateModel()..loadProducts(),
      child: CupertinoStoreApp(),
    ),
  );
}
```

The `create` property is different. Could you correct either the sample code in the [Codelab](https://codelabs.developers.google.com/codelabs/flutter-cupertino/#4) or in the [GitHub repo](https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-01/lib/main.dart)?

**Comment by miquelbeltran** [comment]
The codelab code is no longer hosted in https://github.com/googlecodelabs/flutter-cupertino-store

Instead, now is part of the `flutter/codelabs` repo, here: https://github.com/flutter/codelabs/blob/master_archived/cupertino_store/step_01/lib/main.dart#L15

The code in the codelab document matches the one in the repo (uses `(_) => ..` instead of `(context) => ...` also the code linked in the repo points to the `flutter/codelabs` repo.

I believe this ticket can be closed now.
