### ISSUE TITLE
Windows downloadable ZIP is missing from install flow

### ISSUE THREAD

**Issue by gspencergoog** [flutter/website#2983]
For some reason (the context eludes me: I've been searching for it in issues and chats), the Windows ZIP file was removed from the Windows install flow for Flutter.

It should be put back so that Windows gets the benefits of the downloadable package: we do a lot of work to set that package up in a way that provides for a smooth initial run, including things like minzip, setting up of the IntelliJ project, pre-warming the pub-cache, and other tweaks.

Windows shouldn't be recommending a different flow from other platforms.

It's possible the original motivation for switching to use the clone logic came from this issue (flutter/flutter#38913), but I'm not sure.

**Comment by sfshaza2** [comment]
My understanding is that 7-Zip won't, by default, unpack hidden directories which resulted in a broken build. Further, I gathered an installer for Windows was in the works.

**Comment by gspencergoog** [comment]
No, that's not true: it unpacks hidden directories just fine.

**Comment by gspencergoog** [comment]
And there is an installer in the works, but we shouldn't wait for that: it's going to be a while before it's ready.

**Comment by gspencergoog** [comment]
And now that we've fixed the bug I referenced above, there are no hidden directories anyhow.

**Comment by sfshaza2** [comment]
Fixed.

**Comment by christopherfujino** [comment]
I just realized that although this is indeed fixed in master, the fix did not make the stable release, so the link points to a stable release that still has the issue. I chatted with @gspencergoog offline, and we both think the value of having the link on the website outweighs the severity of the issue. What do you think, @timsneath?

**Comment by timsneath** [comment]
I trust you to make the smart decision here, but curious on the rationale?
We removed this because we worried a good percentage of customers will
unzip the Windows package and then fail because of the .git folder -- has
something changed that gives you confidence that this is a non-issue? Is
there something else that weighs against this that I'm missing?

**Comment by christopherfujino** [comment]
See https://github.com/flutter/flutter/issues/38913 for further context, from that thread the only situation we could think of where it would break would be users copying and pasting the contents to another location in their file manager missing the hidden folders.

**Comment by liyuqian** [comment]
Just for reference: our metrics confirmed a 3x increase of downloads when this issue's fix https://github.com/flutter/website/pull/2984 was merged on 9/10/2019. That is, compared to the [trend](https://data.corp.google.com/sites/3ch2p8hjbetu/stage_2_trial/) since https://github.com/flutter/website/commit/b202bc3553f49ebc1dd09419a7971c7ae646f0cf, our download button click rate tripled from 0.16 to 0.45, and the download actions tripled from 1193 to 3499.
