### ISSUE TITLE
CI: ensure that code-excerpt freshness is checked

### ISSUE THREAD

**Issue by chalin** [flutter/website#3075]
- [ ] Re-adjust `tool/refresh-code-excerpts.sh` (following changes made in #2353) so that it exits with 1 when some excerpts are refreshed.
- [ ] Invoke `tool/refresh-code-excerpts.sh` from `tool/check-code.sh`

(More work needs to be done to `tool/refresh-code-excerpts.sh` so that it doesn't pick one `pub` version over another, but we'll address that in the scope of #3087.)

**Comment by legalcodes** [comment]
`Re-adjust tool/refresh-code-excerpts.sh (following changes made in #2353) so that it exits with 1 when some excerpts are refreshed.`

Sorry, I know I'm missing something obvious -- in what circumstances do we need `refresh-code-
excerpts` to exit 1 when excerpts *are refreshed* ? The purpose of `refresh-code-excerpts` is to refresh the excerpts, why should it fail when certain excerpts refresh?

**Comment by legalcodes** [comment]
Is the idea that,  only when `check-code` runs `refresh-code-excerpts`, and `refresh-code-excerpts` finds that some excerpts were not fresh,`refresh-code-excerpts` exits 1 to tell `check-code` that excerpts need to be refreshed?

**Comment by chalin** [comment]
Right!

**Comment by chalin** [comment]
(When we're running the script locally, to refresh code excerpts, it doesn't matter what the exit code is.)
