### ISSUE TITLE
Replace `<latest version>` with liquid variables in non-running examples

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3340]
## The Problem
Package versions in example code should be up-to-date, and currently we manage this  manually. 

## Proposed Solution
Update package versions once in a liquid variable, so any change is propagated across instructions that refer to "the latest version of x package". Whenever we don't want to use a latest stable version, we can use the version number explicitly in place of the liquid variable. 

For reference, see https://github.com/flutter/website/pull/3294/files.

**Comment by sfshaza2** [comment]
This is a particularly bad idea, in my opinion. When changing the major version number of a package, it's often because API has changed and the app may well fail.

Here's what I wrote on that PR:
Hi, @includecmath! Using the latest version is not always the best case. APIs can change between versions and break your code. You can read more about it on dart.dev and the site it links to that talks about semantic versioning: https://dart.dev/tools/pub/pubspec#version
Also, this page that talks about dependency versioning: https://dart.dev/tools/pub/dependencies#version-constraints

**Comment by legalcodes** [comment]
I think this matter was clarified in the issue referenced -- no one's proposing using latest and/or breaking changes for fixed examples. Rather, where we are merely referencing a latest version, we might be able to indicate that better to the user and even save them a click, as it were.

**Comment by legalcodes** [comment]
E.g. see https://github.com/flutter/website/pull/3783/files#diff-fa8eef8cbacac37fd5c863b0261862fdL24

`You can find the latest version of the
http package on pub.dev.`

**Comment by sfshaza2** [comment]
As long as we're changing it in sample pubspecs, and not in actual running examples, I'm all for it. In fact, I like it very much.

**Comment by miquelbeltran** [comment]
I've checked where the `<latest version>` is used and found the following code examples in the repo:

- https://github.com/flutter/website/blob/c87d537e15e7d0e365c6186222a0006ef2d8365e/src/cookbook/design/package-fonts.md?plain=1#L57
- https://github.com/flutter/website/blob/c87d537e15e7d0e365c6186222a0006ef2d8365e/src/data-and-backend/json.md?plain=1#L262
- https://github.com/flutter/website/blob/c87d537e15e7d0e365c6186222a0006ef2d8365e/src/cookbook/testing/unit/introduction.md?plain=1#L45
- https://github.com/flutter/website/blob/c87d537e15e7d0e365c6186222a0006ef2d8365e/src/cookbook/maintenance/error-reporting.md?plain=1#L62
- https://github.com/flutter/website/blob/c87d537e15e7d0e365c6186222a0006ef2d8365e/src/cookbook/maintenance/error-reporting.md?plain=1#L62

All of them could be replaced by running the commands `flutter pub add <dependency>` or `flutter pub add dev:<dependency>` instead of asking developers to add them to the pubspec manually, which requires going to pub.dev to copy/paste the version.

This is the approach we have been using lately in codelabs.

What do you think about this change?

**Comment by parlough** [comment]
We've been updating to using `flutter pub add` as we touch older samples, but haven't had the chance to go through them all yet. It would be great to update them all!

There's a few others, such as this [`url_launcher` example](https://docs.flutter.dev/testing/oem-debuggers#debugging-with-android-gradle-android) that mention a specific version and don't use `flutter pub add` yet that would be nice to update as well.

**Comment by miquelbeltran** [comment]
Are there any other cases that should be covered, or is everything already fixed with #8950 ?

**Comment by parlough** [comment]
I think you covered most cases and the remainder can probably be addressed individually if found. Thanks so much!

Fixed by https://github.com/flutter/website/pull/8950
