### ISSUE TITLE
'Flutter widget index' page issue

### ISSUE THREAD

**Issue by mingsai** [flutter/website#3362]
Page URL: https://flutter.dev/docs/reference/widgets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/reference/widgets.md

Description of issue:
Many of the widgets are missing sample code and videos. A good example is when a widget of the week appears and is not linked back to the API/Widget reference document. FractionallySizedBox, for example, has a video somewhere but not on the reference page. 

Report a bug option exists only on the top-level page of the docs area. It might work better if one could report a problem directly from the reference pages.

**Comment by sfshaza2** [comment]
Hi @mingsai! I just went to the widget index page and from there clicked the FractionallySizedBox link to the API docs. At the top of the FractionallySizedBox API page, is the embedded video of the Widget of the Week for this widget.

Maybe I'm not understanding your issue? Though, your point about not being able to file an issue from the API reference pages is correct. This is because it's actually two separate websites. The flutter.dev website has codelabs, tutorials, how-to, and conceptual docs. The api.flutter.dev docs are generated and maintained by engineering. You file flutter.dev bugs on the flutter/website repo and you file API reference docs on the flutter/flutter repo.

**Comment by sfshaza2** [comment]
Closing.
