### ISSUE TITLE
List products for sale - product_list_tab.dart

### ISSUE THREAD

**Issue by aureliendebord** [flutter/website#3475]
This code from the tutorial cannot be run:

```
class ProductListTab extends StatelessWidget {
 @override
 Widget build(BuildContext context) {
   return CupertinoPageScaffold(
     child: Consumer<AppStateModel>(
       builder: (context, child, model) {
         final products = model.getProducts();
         ...
```

Output: Try correcting the name to the name of an existing method, or defining a method named 'getProducts'

Changing the order of the build parameters is ok:
`builder: (context, model, child)`

**Comment by sfshaza2** [comment]
Thanks for catching that, @aureliendebord!

**Comment by domesticmouse** [comment]
I believe this is now fixed in the [Building a Cupertino app with Flutter](https://codelabs.developers.google.com/codelabs/flutter-cupertino/index.html#0) codelab. The [github repo](https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-06/lib/product_list_tab.dart#L25) has also been updated.
