### ISSUE TITLE
Document expected theme info for Android themes and splash screens

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/website#3633]
Splash behavior on Android requires careful matching of some display properties between the "launch theme" and whatever `Activity` displays Flutter, e.g., `FlutterActivity`.

This ticket is to consider documenting those nuances in the website guide for splash screens.

For example, depending on which base theme is chosen for the launch theme, developers may need to add the following so that the launch theme flows content beneath the status bar:

```
<item name="android:windowDrawsSystemBarBackgrounds">false</item>
```

The above issue was discovered here: https://github.com/flutter/flutter/issues/47634#issuecomment-576938513

When handling this ticket, the developer should consider whether Flutter can reasonably document these nuances effectively, or if the possibilities are so diverse that the guide should simply inform the app developer that they must make the launch theme match the `Activity` in whatever ways are needed. Flutter shouldn't attempt to extensively document Android style nuances in perpetuity.

**Comment by Hixie** [comment]
See also https://github.com/flutter/flutter/issues/47634#issuecomment-574389942

**Comment by narcodico** [comment]
Hey @Hixie @matthew-carroll !

Struggling with running android app's launch screen in full screen mode. All proposed solutions or workarounds don't seem to work. 

Would like to be able to have the startup experience completely full screen since the app itself is running in full screen as well(basically it makes use of `SystemChrome.setEnabledSystemUIOverlays([])`)
Unfortunately the android launch screen starts with the action bar and status bar both visible and then switching to the splash screen they both get removed which obviously it's visually unpleasant. Not to mention that the centered logo jumps as described in https://github.com/flutter/flutter/issues/47634

Is this even possible to achieve with flutter ? To me this should be something really easy to set up since most modern apps(if not all) are having a full screen launch + splash screen experience that is fluent.

You can find a demo app [here](https://github.com/narcodico/splash_demo) showcasing the flaws I described.

This is currently a blocker for launching an app so any help is welcome!

**Comment by matthew-carroll** [comment]
I don't have the bandwidth to dig into this. However, if you are seeing an actionbar before *before* your splash screen then something very strange is going on. The process that happens at the beginning of an app is:

Android launch screen > Android view > Flutter UI

An Android launch screen can only display a bitmap, so I have no idea how an actionbar would appear at that stage.

Perhaps the actionbar is showing up after the launch screen, during the Android view stage. If that's the case then the issue is with your Android theme. You'll need to adjust your `styles.xml` to prevent an actionbar from being displayed. You should be able to use your `styles.xml` to also make things fullscreen, if desired.

I don't recall if we have a solution to the slight jump that occurs between the launch screen and the Android view.

**Comment by matthew-carroll** [comment]
Also @narcodico the issue that is linked in my original post, as well as @Hixie's comment seems to indicate the answer to solve the "jumping" issue.

**Comment by narcodico** [comment]
Thanks @matthew-carroll for taking the time to answer. As I mentioned, all the proposed solutions don't work for me. Would you mind running the sample I linked in my original comment above to see exactly what I'm talking about ?

**Comment by camsim99** [comment]
Splash screens are no longer used in Flutter, so there is no need to document these nuances. Those experiencing issues with splash screens should migrate to use launch themes/screens.
