### ISSUE TITLE
'Developing packages 

### ISSUE THREAD

**Issue by jm-jisc** [flutter/website#3912]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/developing-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/developing-packages.md

Description of issue:

.idea/modules.xml, **.idea/modules.xml**, .idea/workspace.xml
A hidden folder containing configuration files for the IntelliJ IDEs.

Duplicated ./idea/modules.xml

**Comment by sfshaza2** [comment]
Yup, a minor oopsie. PRs welcome!

**Comment by jm-jisc** [comment]
> Yup, a minor oopsie. PRs welcome!

Shall I create one?

**Comment by sfshaza2** [comment]
It's up to you! You are welcome to, but it's not obligatory. If you do, modify the sentence a tad:

Instead of:
A hidden folder containing configuration files for the IntelliJ IDEs.

Something like:
Hidden folders containing configuration files for the IntelliJ IDEs.

Or you can even spell out:
...for the Android Studio and IntelliJ IDEs.

**Comment by sfshaza2** [comment]
It's been fixed (though the text could be improved).
