### ISSUE TITLE
'Flutter for web developers' page issue

### ISSUE THREAD

**Issue by 01abhishekjain** [flutter/website#3941]
Page URL: https://flutter.dev/docs/get-started/flutter-for/web-devs.html#styling-and-aligning-text
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/flutter-for/web-devs.md

Description of issue:
In this section, it is mentioned that 
> ...font and **color** properties are individual properties of a TextStyle child of a Text widget.

However, in the proceeding example, the **color** is set, not as a property of the `TextStyle` child, but as a property of `Text` widget itself.

**Comment by parlough** [comment]
Taking a look at the sample, it seems properties are controlled with `TextStyle` rather than on the `Text`. The color not in `TextStyle` is within the `Container` for the background color. Perhaps the sample was adjusted when code excerpts were added to test the code.

Thanks again for opening an issue!
