### ISSUE TITLE
'Create lists with different types of items' page issue

### ISSUE THREAD

**Issue by essuraj** [flutter/website#3985]
Page URL: https://flutter.dev/docs/cookbook/lists/mixed-list.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/lists/mixed-list.md

Description of issue:
demo is blank

**Comment by sfshaza2** [comment]
Do you mean that the DartPad instance is blank?  I am seeing code and running it successfully.

@RedBrogdon @johnpryan, any idea what might cause this?

**Comment by essuraj** [comment]
shouldn't the dart pad code show some list?

**Comment by sfshaza2** [comment]
Yes, and I do. Here's what I see. (I had to crop the image because it does't all fit on my macbook.)

<img width="794" alt="Screen Shot 2020-04-22 at 7 39 33 PM" src="https://user-images.githubusercontent.com/44418985/80053199-30cd1780-84d1-11ea-967a-237e3e857dd2.png">

I suspect that you are experiencing some problem with getting data from the back-end, which is why I asking those three engineers who implement DartPad.

**Comment by johnpryan** [comment]
@essuraj are you running any ad blockers? Which version of Chrome are you using?

**Comment by essuraj** [comment]
@johnpryan I am using ublock on Chrome  Version 81.0.4044.113 (Official Build) (64-bit). i disabled it to check and had the same errors/warnings.. also tried in firefox with same warnings/.error and no adblock... after a while it was fixed so i closed the issue.
