### ISSUE TITLE
Add link to 'Retrieve the value of a text field' from 'Build a form with validation' page

### ISSUE THREAD

**Issue by lukepighetti** [flutter/website#4149]
Page URL: https://flutter.dev/docs/cookbook/forms/validation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/validation.md

Description of issue:

There's no description of how to get form values

**Comment by sfshaza2** [comment]
This seems entirely reasonable. Perhaps the example can be updated to print the content of the text field on a submit.

**Comment by JuYeong0413** [comment]
There is [Retrieve the value of a text field](https://flutter.dev/docs/cookbook/forms/retrieve-input) page in the [cookbook forms](https://flutter.dev/docs/cookbook/forms) category with interactive example of getting form values.

Since it is under the same category with [Build a form with validation](https://flutter.dev/docs/cookbook/forms/validation) page, I wonder whether it will be meaningful to print the content of the text field under the validation topic.

**Comment by eseidel** [comment]
Another fix would be to just link to these samples, which seem pretty good (but took me a long time to finally find):
https://github.com/flutter/samples/blob/main/form_app

**Comment by atsansone** [comment]
Fixed in #8940
