### ISSUE TITLE
'Build and release an Android app' page issue

### ISSUE THREAD

**Issue by prabnur** [flutter/website#4392]
Page URL: https://flutter.dev/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue:

So that page shows you how to sign the app using a key in a keystore made with Java's keytool. However the recommended way to publish an android app according to Google is to build and release an app bundle. This requires that you allow Google to manage the app signing for you. And it is also recommended by Google to do so even if the developer was publishing an APK.

 So is the the whole app signing from the developers side really even necessary?

**Comment by sfshaza2** [comment]
@tvolkert?

**Comment by tvolkert** [comment]
@xster

**Comment by xster** [comment]
I don't think the instructions are conflicting. FWIW, there might be some slight confusion since there are 2 keys involved when signing Android apps. There's an upload key which you need to sign with before pushing to the Play Store. That key isn't seen by your users however. It's just a way to validate your upload package between you and the Play Store. The Play Store then resigns the whole thing with the Play Store managed distribution key. This way you don't end up losing access to your distribution key(and the ability to update your users) if you lose your computer but you're still authenticated between your machine and the Play Store during the upload. 

Please reopen if I misunderstood your question.
