### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by w-o-j-t** [flutter/website#4399]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:

There is no "dart.exe" in flutter/bin/ path. Neither in downloadable package nor in the stable branch. Description incorrect.

**Comment by sfshaza2** [comment]
@timsneath, you have a Windows machine, yes? Can you comment?

**Comment by timsneath** [comment]
Ugh -- this was reverted out of the release. @franklinyow @pcsosinski -- see the URL above; should this now say 1.21?

**Comment by pcsosinski** [comment]
does a version requirement work on this page or will it just be more confusing?

**Comment by timsneath** [comment]
Yeah, we already had a version requirement (1.19.0-dev), so we just need to update it. What should it now say?

**Comment by pcsosinski** [comment]
oh I see the section in the webpage referring to that now.   TBH I'm not sure where the revert happened and am not tracking the re-enablement of the behavior.  can you point me to the issue(s) covering it?

the original description also references stable, which would be 1.17, so that seems expected.

**Comment by franklinyow** [comment]
I did some digging, I think the page is accurate but could be improve
The stable download ver 1.17 does not have dart.exe is what we expected.  It was not release until 1.19-dev
The up coming **stable** 1.20 will not have dart.exe because we backed it out. [#42748](https://github.com/dart-lang/sdk/issues/42748)

In summery, and build from 1.19.0-dev and after that is from a dev branch should have this, not on stable

**Comment by sfshaza2** [comment]
Thanks for clarifying, @franklinyow and @pcsosinski!

**Comment by timsneath** [comment]
Closing as stale.
