### ISSUE TITLE
Move diagrams out of src

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#4974]
See https://github.com/dart-lang/site-www/pull/2742, which fixes https://github.com/dart-lang/site-www/issues/1920.

**Comment by sfshaza2** [comment]
OK, I had to read through the Dart PRs/issues to get more context. This isn't removing the .graffle (Omnigraffle) files out of the repo, it's just moving them from /src/_diagrams to /diagrams. Yep, that seems fine.

We just needed a place to stash the source for our diagrams but these diagrams aren't actually used to generate the site. And, moving forward, we are now using draw.io to generate diagrams. But we still plan to save the original PNG diagrams (generated by draw.io) into the /diagrams folders, because if someone changes the _size_ of a PNG diagram, we lose the ability to edit it.
