### ISSUE TITLE
'Work with WebSockets' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#5068]
Page URL: https://flutter.dev/docs/cookbook/networking/web-sockets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/web-sockets.md

Description of issue:

Can't this code lead to a memory leak:

```dart
  @override
  Widget build(BuildContext context) {
    final title = 'WebSocket Demo';
    return MaterialApp(
      title: title,
      home: MyHomePage(
        title: title,
        channel: IOWebSocketChannel.connect('ws://echo.websocket.org'),
      ),
    );
  }
}
```

Usually we create new Streams on `initState`, since `build` should be idempotent.

**Comment by sfshaza2** [comment]
Can you weigh in, @johnpryan?

**Comment by johnpryan** [comment]
I think you're onto something. The `connect()` function could technically get called multiple times since it's invoked in a build() method. (In this sample, it probably won't because nothing in the parent widget will change.) 

 Instead, the call to `connect()` could be moved into an `initState()` and cleaned up in by overriding `dispose()`. 

For bonus points, the `channel` parameter could still be exposed by the HomePage constructor as a String instead of a channel, and HomePage could close the old channel and open a new one by overriding `didUpdateWidget`.

**Comment by feinstein** [comment]
Yes, and even if it won't be rebuilt, the examples should reflect best practices, so begginers don't get in trouble. In special since many don't know `build` should be indempotent.

**Comment by sfshaza2** [comment]
No question! Which of you wants to fix this?  :)

**Comment by atsansone** [comment]
Examples have been updated since this ticket. Issue no longer applies. Closing.
