### ISSUE TITLE
Explain 'Unbounded height/width' errors

### ISSUE THREAD

**Issue by filiph** [flutter/website#5323]
We have Katie Lee's excellent [article on debugging layout issues](https://medium.com/flutter/how-to-debug-layout-issues-with-the-flutter-inspector-87460a7b9db#1de2). I would like to make a video deep dive into one particular issue: the unbounded height error.

In short: This error comes up when something like a `ListView` or `Column` is placed into another `ListView` or `Column`.* It is often resolved by putting a `Flexible` or `Expanded` around the inner `ListView` or `Column`.** Katie's article gives more practical advice.

*) Are there other examples?
**) Are there other frequent solutions? SizedBox?

I'd like to get to the bottom of the issue. As a developer, I'd like to know _why_. In Katie's article, this is partially captured with this aside:

> Why doesn’t `Column` just limit the height of its children to its own height?
>
> You can end up in a situation where the first child takes up all the space, forcing the second child to have `0` height. And you wouldn’t immediately know about it because no errors are thrown.

I would like @Hixie to expand on that, iteratively, in this issue. Hopefully, this will be enlightening not only for me, and will live here forevermore. (The most immediate goal is for Filip to make a 2 minute explainer video, though.)

Let's imagine an alternate reality, in which `Column` *does* limit the height of its children to its own height. What does that look like for the developer, exactly?

Let's talk about something like this:

```dart
Column(
  children: [
    Text('A list of things:'),
    MyScrollingWidget(),
    Text('The end'),
  ],
),
```

`MyScrollingWidget` looks like this:

```dart
class MyScrollingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemBuilder: (context, index) {
        return ListTile(title: Text('Item $index'));
      },
    );
  }
}
```

[Here](https://dartpad.dartlang.org/c45e5637ff9e7306792c94a399d93da6)'s the fixed version of the app in DartPad.

**Comment by Hixie** [comment]
In the example you give, if all three children were limited to the height of the Column, then the first Text would be as high as a line of text, the second Text would be as high as a line of text, and the MyScrollingWidget would be as high as the column. If we say the text is 10px high, and the column is 100px high, that means the contents of the 100px high column would be... 120px. That's presumably not what anyone intended.

**Comment by Hixie** [comment]
> *) Are there other examples?

It happens for any render object that tries to be as big as possible (sets its height to the constraints' max height), when put inside a render object that tells its children they can be as big as possible (sets the child's constraints max height to infinity).

> **) Are there other frequent solutions? SizedBox?

It really depends on what the developer wants the UI to be. Part of the reason we throw here is that we can't figure out what the right behaviour is because the developer hasn't told us enough to do what they want.

**Comment by filiph** [comment]
Great! 

> In the example you give, if all three children were limited to the height of the Column, then the first Text would be as high as a line of text, the second Text would be as high as a line of text, and the MyScrollingWidget would be as high as the column. If we say the text is 10px high, and the column is 100px high, that means the contents of the 100px high column would be... 120px. That's presumably not what anyone intended.

Additional questions:

1) Why can't the `Column` say to `MyScrollingWidget`: "You want 100px, but you only get 80px."?
2) Why can't the `Column` look at the two `Text`s with their set "tight" sizes first, and then just tell `MyScrollingWidget`: "You get 80px."?

I think I know the answers, but I would like to get this right.

**Comment by Hixie** [comment]
> Why can't the Column say to MyScrollingWidget: "You want 100px, but you only get 80px."?

Two reasons, First: how would it know to do so? Why should MyScrollingWidget get 20px less space than it wants, rather than making each Text have 10px less space than they want, say?

But more importantly, second: because Flutter's rendering model is single-pass, constraint-down, geometry-up. To tell the child that it can only get 80px, it must specify a max height of 80px in the constraints. That's the entire purpose of the constraints.

> Why can't the Column look at the two Texts with their set "tight" sizes first, and then just tell MyScrollingWidget: "You get 80px."?

From the Column's perspective, it has three children. They all are given identical constraints, and they all give back a fixed size. How can it distinguish them? There's nothing special about MyScrollingWidget. The Text widgets don't have a "tight" size any more than the MyScrollingWidget. "Tightness" in Flutter refers to the constraints -- a "tight" constraint is one that specifies equial min and max constraints (e.g. min height = max height). A "loose" constraint is one that gives the child a choice of any size, e.g. "anything from 0 to 100 pixels" or "anything from 0 to infinite pixels" or "anything between 10 and 20 pixels". Whatever the constraints you give a child, the child _must_ select a Size that fulfills those constraints. Sizes are always just two non-negative finite lengths (width and height).

**Comment by filiph** [comment]
Yes, thank you!

Is it fair to say, with perhaps a degree of simplification, that in the alternate universe in which `Column`>`ListView` "just worked" (i.e. you could add a ListView into a Column and there'd be no unbounded error):

1) Flutter would be much slower (multiple-pass layout), OR
2) Column would crash anyway because it would "run out of vertical pixels" (e.g. no pixels left for `Text('The end')` above)?

If so, I have follow-up questions.

* For 1), how _much_ slower would it be? I realize this is pure speculation. But I think it's fair, for someone coming from web development, to ask that question. How come the web can be multi-pass (?) and still be comparably fast?
* For 2), why do we prefer the `Unbounded height` error over the `I ran out of pixels` error?
* How come that adding a `Flexible`/`Expanded` fixes this?

Thanks again for your patient explanation, it is really helpful.

**Comment by Hixie** [comment]
> in the alternate universe in which `Column`>`ListView` "just worked" (i.e. you could add a ListView into a Column and there'd be no unbounded error)

If there's no error, that means we do something. What would we do? I don't understand what the "correct" rendering would be.

**Comment by filiph** [comment]
For the sake of argument, let's say that doing

```dart
Column(
  children: [
    Text('A list of things:'),
    MyScrollingWidget(),
    Text('The end'),
  ],
),
```

would do what the average beginner expects it to do, which is to say, there's no error, the two `Text` widgets are at their intrinsic height, and between them the `MyScrollingWidget` takes up the rest of the vertical space.

I know this is an arbitrary scenario. My hypothesis is that, by examining the alternate universe, the developer might better internalize the choices of the actual one.

**Comment by Hixie** [comment]
I don't understand how Column could know that MyScrollingWidget should act as if it was marked "Expanded". What's special about MyScrollingWidget? (Would it still be special if, e.g., it was wrapped in a Padding?)

I suppose we could have an entirely different layout model, in which MyScrollingWidget somehow (e.g. by multiple passes as you suggest) told the Column that it was special. Assuming we had that:

> * For 1), how _much_ slower would it be?

I don't know if it would be slower, because I don't know what the model being proposed actually is. Maybe it would be faster, but would have some other trade-off. Maybe it would just be better all around. :-)

> How come the web can be multi-pass (?) and still be reasonably fast?

I disagree with the premise of the question. The web is orders of magnitude slower at layout. It's one of the things that led to Flutter being created in the first place.


> * For 2), why do we prefer the `Unbounded height` error over the `I ran out of pixels` error?

I don't know that we prefer either. Either way, there's an error.


> * How come that adding a `Flexible`/`Expanded` fixes this?

What "Expanded" says is "instead of telling the child that it can have any size, tell it what size to be by laying everyone else out first, then splitting the remaining space among the Expanded children". So the MyScrollingWidget in that case would be told "you must be 80 pixels high".

**Comment by filiph** [comment]
Thanks! I think that answers all my questions. I'll leave this open until I either have more questions or I deliver the explanatory content.

**Comment by sfshaza2** [comment]
I very much love this!

**Comment by filiph** [comment]
The video just landed:
https://www.youtube.com/watch?v=jckqXR5CrPI

I'm closing this bug. But I might write an article later for people who prefer reading over watching video.

**Comment by arulmani33** [comment]
> The video just landed:
> https://www.youtube.com/watch?v=jckqXR5CrPI
> 
> I'm closing this bug. But I might write an article later for people who prefer reading over watching video.

I'm an android native developer after  I switch to flutter I have been seen this issue is so far and yeah I found a solution but your example is simply awesome. Thanks for the explanation
