### ISSUE TITLE
Add details on installing Android SDK Command-line tools to 'Linux install' page

### ISSUE THREAD

**Issue by martinkilmartin** [flutter/website#5368]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue: Linux OS may need to install **Android SDK Command-line tools** from **Android SDK Manager**.

See https://stackoverflow.com/a/64162776/14885007

**Comment by micpap25** [comment]
![image](https://user-images.githubusercontent.com/34077605/111319195-1dbcbc00-863c-11eb-98ca-6d60b0e4e478.png)

This is the section we have for android studio; on one hand, your issue is already resolved and the method to install the command-line tools is mentioned. On the other hand, I think it would be useful to flesh out this section and maybe make it more robust.

I don't know if we should be explaining how to re-install missing Android SDK tools in the installation page. @sfshaza2 any thoughts?

**Comment by martinkilmartin** [comment]
I'm attempting to install  Android SDK Command-line tools and Android SDK Manager without installing Android Studio as it takes excessively large disk space and I already have a preferred IDE. The time I've spent attempting to set up a Flutter dev environment without Android Studio encourages me to switch back to React Native or Ionic.

**Comment by atsansone** [comment]
As noted on this page, Flutter requires the full installation of Android Studio. Closing this issue as Won't Do.
