### ISSUE TITLE
Fix badly formatted links

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#5387]
```
$ fgrep -Rl "][" _site | fgrep ".html"
_site/docs/development/tools/devtools/memory.html
_site/docs/development/tools/sdk/release-notes/release-notes-1.20.0.html
_site/docs/development/tools/sdk/release-notes/release-notes-1.22.0.html
_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.12.13.html
_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.9.1.html
_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.17.0.html
_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.2.1.html
_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.5.4.html
_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.7.8.html
_site/docs/development/tools/sdk/release-notes/release-notes-2.0.0.html
_site/docs/development/tools/sdk/release-notes/release-notes-1.12.13.html
_site/docs/development/tools/sdk/release-notes/release-notes-1.17.0.html
_site/docs/development/tools/sdk/release-notes/release-notes-1.9.1.html
_site/docs/development/accessibility-and-localization/internationalization.html
_site/docs/development/add-to-app/performance.html
_site/docs/development/platform-integration/web.html
_site/docs/resources/faq.html
_site/docs/release/breaking-changes/1-22-deprecations.html
_site/docs/release/breaking-changes/material-chip-button-semantics.html
_site/docs/release/breaking-changes/hero-controller-scope.html
_site/docs/release/breaking-changes/bottom-navigation-title-to-label.html
_site/docs/cookbook/persistence/sqlite.html
_site/docs/perf/rendering/ui-performance.html
_site/docs/perf/faq.html
_site/docs/get-started/flutter-for/android-devs.html
_site/docs/get-started/flutter-for/ios-devs.html
_site/docs/get-started/flutter-for/xamarin-forms-devs.html
_site/tos.html
```

**Comment by sfshaza2** [comment]
Status

Files crossed out are actually ok and valid. Since the release notes, changelogs, etc, are generated from GitHub, I am loathe to change that text to avoid "][". (In fact, I've been asked not to.)

In the case of the internationalization page, it occurs in legitimate code blocks.

- [x]_site/docs/development/tools/devtools/memory.html - Fixed in PR https://github.com/flutter/website/pull/5457
- <s>_site/docs/development/tools/sdk/release-notes/release-notes-1.22.0.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.12.13.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.9.1.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.17.0.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.2.1.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.5.4.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/changelogs/changelog-1.7.8.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/release-notes-2.0.0.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/release-notes-1.12.13.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/release-notes-1.17.0.html</s>
- <s>_site/docs/development/tools/sdk/release-notes/release-notes-1.9.1.html</s>
- <s>_site/docs/development/accessibility-and-localization/internationalization.html</s>
_site/docs/development/add-to-app/performance.html
_site/docs/development/platform-integration/web.html
- [x]_site/docs/resources/faq.html - Fixed in PR https://github.com/flutter/website/pull/5469
_site/docs/release/breaking-changes/1-22-deprecations.html
_site/docs/release/breaking-changes/material-chip-button-semantics.html
_site/docs/release/breaking-changes/hero-controller-scope.html
_site/docs/release/breaking-changes/bottom-navigation-title-to-label.html
_site/docs/cookbook/persistence/sqlite.html
_site/docs/perf/rendering/ui-performance.html
_site/docs/perf/faq.html
_site/docs/get-started/flutter-for/android-devs.html
_site/docs/get-started/flutter-for/ios-devs.html
_site/docs/get-started/flutter-for/xamarin-forms-devs.html
_site/tos.html
