### ISSUE TITLE
Clarify how Flutter on the web builds and bundles `html` and `canvaskit` on 'Web renderers' page 

### ISSUE THREAD

**Issue by mariamhas** [flutter/website#5470]
Page URL: https://docs.flutter.dev/platform-integration/web/renderers
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/web-renderers.md

Feedback: Regarding the default Flutter web render “auto”, does it actually build and bundle both a html and canvaskit build into the same bundle that you then upload to your server? And then it download the right build based on target device downloading/using the web app/site as described in https://flutter.dev/docs/development/tools/web-renderers? I assume so, it is kind of implied in the docs, but not 100% clear. If does so (no idea how it would work if does not) I think it should say so as well in the docs.

**Comment by johnpryan** [comment]
At first glance, I don't see an answer in the [Web Renderer Options](https://docs.google.com/document/d/1aY0iU16wf_sdT7nwfpjgT-IatHNfF3slTiYHKmxcIog/edit) design doc - I'll need to do some more digging. 

@yjbanov Does `auto` affect the bundle in some way? Or is the renderer chosen at runtime?

**Comment by sfshaza2** [comment]
Based on Yegor's answer (for another issue), no. It locks the build in to one or the other. I've copied the following response from Yegor from PR https://github.com/flutter/flutter/issues/76652#issuecomment-786086430:

We'd like to support this as this would allow one to boot the app quickly without waiting for CanvasKit to download (when the browser cache is empty) then load CanvasKit in the background, but it's not a small project. As @TahaTesser says once a renderer is picked we're locked into it, sometimes because we choose at compile time (when you pick "html" or "canvaskit" explicitly), but also because the application holds references to renderer-specific class implementations (e.g. Paint is implemented by CanvasKit-specific CkPaint or HTML-specific SurfacePaint; not an easy fix). So there's quite a bit of design work to do before we even begin the implementation. We have other ideas too, such as bringing down CanvasKit size, adding API for app loading indicators. We haven't decided what combination of solutions we will attempt, even though we definitely want to make progress.

One thing that might help is in --web-renderer=auto mode (the default) before the app is loaded (i.e. before main.dart.js) you can set window.flutterWebRenderer to "html" or "canvaskit" in JavaScript. This way you can decide at runtime what renderer is appropriate for that instance of the app. You can't change it after the app loads, but it could provide some flexibility, such as:

Maintain your own list of browsers/OSes/devices/regions where your app works better in HTML vs CanvasKit
Implement a custom strategy for loading CanvasKit. For example, if the cache is empty you can load the app in HTML mode, then kick off a fetch to get CanvasKit. When it's available, you can pop-up a message to the user asking to reload the app to get the full experience. Since there's no explicit browser cache API you can remember whether you previously downloaded CanvasKit in localStorage, so next time the app loads you check localStorage and go straight to CanvasKit.
Have multiple entry points for your app hosted on different URLs, one advertised as "installed app" (i.e. PWA), and one advertised as "ephemeral". The PWA version could always include CanvasKit, while ephemeral one prefers HTML.

---

Also, someone used this answer to [submit PR 5565](https://github.com/flutter/website/pull/5565) to the web renderer page. It looks good to me and I've asked @yjbanov to look at it, but maybe you can do that, @johnpryan?

**Comment by johnpryan** [comment]
@yjbanov @hterkelsen is it correct to say that the `main.dart.js` file is the same and the CanvasKit script is only loaded if it is chosen by the engine at runtime?

**Comment by atsansone** [comment]
Fixed in:

- https://github.com/flutter/website/pull/5565
- https://github.com/flutter/website/pull/5079

Closing issue.
