### ISSUE TITLE
Correction in Image required for "Layouts in Flutter" page

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/website#5586]
In the second image of the page https://flutter.dev/docs/development/ui/layout#lay-out-multiple-widgets-vertically-and-horizontally, i.e. the image below "The left column’s widget tree nests rows and columns." text, the bottom right section of the image requires correction.

![pavlova-left-column-diagram](https://flutter.dev/assets/ui/layout/pavlova-left-column-diagram-c9bf1a39b39270615ce8e82608952ac3edaa0d1eab8691f8783e6408fdfbdfb3.png)

Following is the corrected image.

![pavlova-left-column-diagram-corrected](https://user-images.githubusercontent.com/8739924/113565402-9229c000-9628-11eb-9a16-00a6eb2a8717.png)

I would suggest opening this page by disabling the dark theme of GitHub.

**Comment by sfshaza2** [comment]
You are correct about the error in the image and thanks for providing a corrected page!

However, when I open the image in GitHub, it does not use the dark theme. I never use the dark theme because I have trouble reading it. Are you using it as a default setting on GitHub? If so, I'm not sure what I can do about that.

**Comment by hrishikesh-kadam** [comment]
Disabling the dark theme of GitHub was just a suggestion to see the image more clearly, as it contains transparency.

**Comment by MiraMarshall** [comment]
Closing because this issue has been addressed.
