### ISSUE TITLE
Revisit Gesture Disambiguation on 'Taps, drags, and other gestures' page

### ISSUE THREAD

**Issue by mprogers** [flutter/website#5595]
Page URL: https://docs.flutter.dev/ui/advanced/gestures
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/gestures.md

Description of issue: I found the discussion of disambiguation to be a bit confusing. It talks about multiple GestureDetectors. How would this be structured? A GD containing a child that is a GD? Wouldn't it be more likely that the programmer would have 1 GD, with multiple callbacks? Does the gesture arena apply in this situation?

**Comment by sfshaza2** [comment]
@Hixie, who can speak to this?

**Comment by Hixie** [comment]
The gesture arena applies in both cases described. It's common to have nested gesture detectors (e.g. a list view with a button inside). @goderbauer owns this part of the codebase.

**Comment by atsansone** [comment]
@goderbauer : Would you have any suggested changes for [this passage](https://docs.flutter.dev/ui/advanced/gestures#gesture-disambiguation)?

**Comment by goderbauer** [comment]
I would add some examples (maybe after the first sentence) explaining why there could be multiple gesture recognizers covering the same location on screen: You could have nested gesture recognizers (e.g. for a ListTile you may have a tap recognizer that responds to the entire ListTile and a nested one around a trailing icon button; the screen rect of the trailing icon is now covered by two gesture recognizers that need to fight in the arena for who gets to handle the gesture if it turns out to be a tap). Another reason could be you have a single GestureDetector covering a screen area that is configured to handle multiple gestures (e.g. maybe you want to handle a long press and a tap). This gesture detector now sends multiple recognizers (one for taps, one for long presses) into the arena when the user touches this area of the screen. Depending on what happens next with that pointer, one of them will declare victory to handle the gesture - or they may both declare defeat if e.g. the user goes on to perform something that's neither a tap nor a long press.
