### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by alv909** [flutter/website#5609]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Description of issues with this cookbook example:
1) if the environment is set to < 2.12, keyword 'late' will spawn an error in the editor and prevent running the example
2) further, it seems that keyword 'required' needs to be written without '@', because otherwise an error is shown ?
("Try adding either an explicit non-'null' default value or the 'required' modifier.")
3) and last, they parameter key also shows an error ("Error: The parameter 'key' can't have a value of 'null'")

**Comment by parlough** [comment]
Thanks for opening this issue and sorry for the delayed response!

These errors were because the page was updated to use/support [null safety](https://dart.dev/null-safety) which was supported since [Flutter 2](https://medium.com/flutter/whats-new-in-flutter-2-0-fe8e95ecc65) and [Dart 2.12](https://medium.com/dartlang/announcing-dart-2-12-499a6e689c87). Since we've reached a point long past those releases and the rest of the site uses null safety as well, I'm going to close this. Thanks again!
