### ISSUE TITLE
'Introduction to widgets' page issue

### ISSUE THREAD

**Issue by dev-tryit** [flutter/website#5689]
Page URL: https://flutter.dev/docs/development/ui/widgets-intro.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets-intro.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

required -> @required

**Comment by JuYeong0413** [comment]
Since the embedded dartpad is null-safe, `required` is correct. :-)
(If you are using Dart SDK lower than 2.12, then you should use `@required`.)
<img width="1792" alt="Screen Shot 2021-04-27 at 12 51 31 AM" src="https://user-images.githubusercontent.com/33684401/116112873-f48b5300-a6f2-11eb-96e4-0849b70e5f15.png">

See https://dart.dev/null-safety for more information about null-safe Dart.

**Comment by sfshaza2** [comment]
Yes, @dev-tryit, we are in the process of migrating all code to null safety, which is now the version we recommend using. Sorry this bit you.  Closing.
