### ISSUE TITLE
Simplify procedure for updating code samples on flutter/website

### ISSUE THREAD

**Issue by iapicca** [flutter/website#5861]
### this issue is entirely based on my personal opinion

Attempting to fix this [issue](flutter/website#6768)  I submitted for the first time a [PR](https://github.com/flutter/website/pull/5798) for `flutter/website` (that may or may not be successful)
and followed these [docs]( https://github.com/flutter/website#2-clone-this-repo-and-its-submodules) 

I feel that the current steps required for producing a PR is:
- **_overly complex_**
there are at least 9 steps completely unrelated to the actual code change
- **_bloated_**
that require the local installation of 
   - [nvm]( https://github.com/nvm-sh/nvm/blob/master/README.md#installing-and-updating) 
   - `node`
   - [rvm](https://rvm.io/rvm/install#installation) 
   - `ruby` 
   - an **_additional copy of flutter_** (!!!)
- **_flawed_**
following to the letter some steps output errors, only in part fixable by the contributor (and very many warning)

you can find the details in this [comment](https://github.com/flutter/website/pull/5798#issuecomment-849502269)

### expectation

the steps for providing a PR should be 
+ clear
+ streamlined
+ leave the contributor's machine as clean as possible
+ **_does NOT constitute a barrier for contributions_**

### actual

I feel the steps for providing a PR are
- complex
- require many actions unrelated to the actual contribution
- leave the contributor machine bloated with unwanted software
- most importantly **_a strong deterrent from submitting a PR_**

**Comment by micpap25** [comment]
@iapicca ,
I agree that installing all the tools needed to stage the Flutter website is a long process. However, it is a necessary one, as that is the only way to properly stage the Flutter website locally. I'd like to bring up a few points:

1. It is not necessary to install all these tools for the vast majority of PRs. Many PRs require simply editing Markdown files, and perhaps some testing of code within an emulator. Fewer PRs require staging the site.

2. Generally, PRs that require staging the site could be considered more difficult; those that require more expertise. That means usually, people with experience in the flutter/website repositories deal with these issues. While your contribution was important, I think your case is rare, as you took on one of these difficult issues in your very first PR.

3. Additionally, most developers that have the expertise to work on difficult issues generally continue contributing to flutter/website. You treat staging the website as steps 1-9, and making your PR as step 10; consider that many developers don't consider this process "overly complex" or "bloated" because they are fine installing these tools over a long period of time. Developers might also already have many of these tools because these are also useful tools for many kinds of projects.

Again, I agree these steps are complicated, but ultimately it's the process necessary to make major changes to the flutter.dev.

Lastly, I am very interested in this line:

> following to the letter some steps output errors, only in part fixable by the contributor (and very many warning)

Can you specify which steps you are referring to here? Ironing out any errors from the guide might be the best way to simplify the process for the future.

**Comment by iapicca** [comment]
> Can you specify which steps you are referring to here? Ironing out any errors from the guide might be the best way to simplify the process for the future.

@micpap25 
following the link I provided above

> you can find the details in this [comment](https://github.com/flutter/website/pull/5798#issuecomment-849502269)

all these steps output an error

- run before-install.sh FAILED! 
- run install.sh
- run tool/refresh-code-excerpts.sh

moreover

> 1. It is not necessary to install all these tools for the vast majority of PRs. Many PRs require simply editing Markdown files, and perhaps some testing of code within an emulator. Fewer PRs require staging the site.

nevertheless, simply updating a code sample requires the steps I mentioned

casually browsing the issue in this repo it's easy to notice that many of those
are request to update or fix a code sample
no wonder why developers are not submitting PRs

> 2. Generally, PRs that require staging the site could be considered more difficult; those that require more expertise. That means usually, people with experience in the flutter/website repositories deal with these issues. While your contribution was important, I think your case is rare, as you took on one of these difficult issues in your very first PR.

**_requiring expertise_** in the flutter/website repository **_just to fix a broken code sample_** it's the core problem;
consider the possibility that my case might be rare  because 
potential contributor don't submit PR due to the complexity of the process

> 3\. Additionally, most developers that have the expertise to work on difficult issues generally continue contributing to flutter/website. You treat staging the website as steps 1-9, and making your PR as step 10; consider that many developers don't consider this process "overly complex" or "bloated" because they are fine installing these tools over a long period of time. Developers might also already have many of these tools because these are also useful tools for many kinds of projects

this seems a very iffy assumption, but even if it's true, it should not be a given
the instructions provided are fairly easy to read, but outputs errors (at least in my case, see above)
it would be a step forward to have 
- a script to set up the environment (that can be tested, making sure it's error free)
- a script to remove the "potentially unwanted" software

or alternatively if not preferentially 
-  a docker image that envelops the whole process

lastly even assuming that for some, even most, downloading `nvm`, `rvm`, `node` and `ruby`,
the need of _**downloading an additional copy of flutter**_  is still inexplicable for me

**Comment by Hixie** [comment]
I have to be honest, I kinda agree with @iapicca. Setting up Node and Ruby on my workstation so that one can work on a Dart product's web site seems excessive. I've personally avoided doing this for the entire length of the project, instead relying on CI to catch problems I introduce, which isn't a great experience either.

**Comment by micpap25** [comment]
I do want to preface all this by saying, I'm not a Google employee or affiliated with Google; I just do a lot of triage on Dart and Dart-related repositories. 
I'm also sorry if I'm coming off as anti-progress, I'm trying to play devil's advocate a bit because I want to make sure the simplification gets to the root of the issue. 

> while the need for downloading an additional copy of flutter is still inexplicable for me
I'm a bit confused where the instructions say to install a second copy of Flutter; it says that you need to have Flutter, but only need to download it if you don't have it already. Can you specify which line says this?

> a script
I agree that a script could be a compact way of installing all requirements, though it wouldn't solve the _**bloated**_ issue you bring up.

> a docker image
I don't agree as much with this, as this would require installation of Docker, which would be another step that would work against reducing complexity and bloat.

> a GitHub action
I'm not too familiar with GitHub actions, so I'm not going to comment on this.

I think I'm going to step out of this issue and let people with more experience and control than me handle it. Hopefully a solution can be arrived at.

**Comment by iapicca** [comment]
> > while the need for downloading an additional copy of flutter is still inexplicable for me
> 
> I'm a bit confused where the instructions say to install a second copy of Flutter; it says that you need to have Flutter, but only need to download it if you don't have it already. Can you specify which line says this?

@micpap25 
it's in the same logs I provided in the PR's [comment](https://github.com/flutter/website/pull/5798#issuecomment-849502269) under the collapsible `run before-install.sh FIXED!`
I can assure you that I had the master version of flutter already installed under [fvm](https://github.com/leoafarias/fvm)

**Comment by sfshaza2** [comment]
@iapicca, thanks for that last comment! And, yes, that is a great idea for a video. I'm going to add it to a suggestions page.

**Comment by atsansone** [comment]
@iapicca : Did this change meet your needs? Let us know if further action is needed. Thanks!

**Comment by iapicca** [comment]
I don't have the bandwidth to check this right now, 
closing as solved, please reopen if you feel that something else needs to be done
