### ISSUE TITLE
Add details on Snap issues when installing Flutter to 'Linux install' page

### ISSUE THREAD

**Issue by willhaslett** [flutter/website#6460]
### Page URL

https://flutter.dev/docs/get-started/install/linux/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/install/linux.md

### Describe the problem

[A problem with the Snap version](https://github.com/flutter/flutter/issues/72415) of Flutter has been causing problems for people with popular, up-to-date Linux distros for about a year now, and it's not fixed. I'd consider adding a warning about this, or making the manual install the first-listed, preferred method of installation. 

### Expected fix

Unless this problem is really rare, it would be great to have a warning. Since I started with Ubuntu 20, it seems like this may not be rare.

### Additional context

Ubuntu 20, fresh install.

**Comment by danagbemava-nc** [comment]
@willhaslett, thanks for reporting this.

**Comment by MrCsabaToth** [comment]
I'd like to mention https://github.com/flutter/flutter/issues/93495 (which was due to https://github.com/flutter/flutter/issues/93497): at November 10th the most recent version was an August update which contained a version from May. So that's an extra issue if any time in the future the initial version installed by Snap would be outdated. But even if it is not I'll open an issue so it'd be clear to the Flutter newcommers to rely on the Flutter CLI after installation instead of Snap.

**Comment by MrCsabaToth** [comment]
For the record: snap is the preferred method since #4341 (2020 summer). I don't have snap so I can imagine that now the snap builds will come as well a developer might get warnings about new versions both from snap (advising snap refresh) and both from the IDE / Flutter doctor (advising Flutter CLI based refresh).

**Comment by Thalience** [comment]
The flutter snap is again badly outdated, and it seems that nobody cares. PLEASE stop recommending this broken installation method to Linux users.

**Comment by MrCsabaToth** [comment]
The official policy is that the snap is just an installation vehicle. After install the flutter CLI should be used exclusively. See also https://github.com/flutter/website/issues/6499

If we go through the Linux installation methods there's a `flutter doctor` step after installation. Theoretically that should warn the user that the Flutter SDK is not up to date. In my opinion it should be an explicit step after the `flutter doctor` step to perform a `flutter upgrade`. Just to be sure. That would be a workaround if the snap initial install lags behind too much. Any civilized IDE (such as Android Studio or Visual Studio Code w Flutter plugins) also warns the user after some delay about the new version. If the newbie is fast clicking that may come after the IDE suggestion arrives, at which point a generated project could be already an outdated scaffold.

Of course it's a blocker if it's so outdated that with certain distro version it may not even install successfully from snap.

**Comment by Thalience** [comment]
I see that now. Thank you for taking the time to respond! 
I do think that a note to this effect could be added directly to the snap installation instructions.

Or perhaps it is the output of `flutter doctor` that could be improved to show that what it wants to update is not in the snap, but cached in my home directory. If I had installed manually, this would not have been surprising.

**Comment by atsansone** [comment]
This appears to have been fixed in https://github.com/canonical/flutter-snap/pull/78. Closing issue.
