### ISSUE TITLE
Align supported platforms for Flutter & Dart

### ISSUE THREAD

**Issue by khyati82** [flutter/website#6713]
Create & document a process to proactively approach platform misalignments and supported platforms for Flutter & Dart. This is a child issue of master issue flutter/website#6710

**Comment by sfshaza2** [comment]
@mit-mit, can you weigh in here? I think that Dart and Flutter approach this very differently. Dart's approach seems to be "we support the last two major releases of the platform". But Dart doesn't do all of the testing that Flutter does. 

Is there a way to coalesce this info? The Dart info is here:  https://dart.dev/get-dart#system-requirements

And the Flutter info is here (though I am currently updating this page): https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms

**Comment by parlough** [comment]
It sounds like the problem is that we don't really specifically outline Dart's "Supported deployment platforms" anywhere, outside of stating the last two-major browser releases for web deployments. In terms of the site, we've essentially been treating the "SDK system requirements" as the "Supported deployment platforms", maybe because the support for self-contained deployments outside of `dart2js` through `dart compile exe`  is more recent. 

Perhaps the system requirements and supported deployment platforms of Dart are the same, but either way, we should likely call that out better, either on the [Get Dart](https://dart.dev/get-dart) page or through a new page.

**Comment by atsansone** [comment]
@mit-mit : Could you weigh in please?

**Comment by mit-mit** [comment]
Dart lists which platforms may be used for Dart development here:
https://dart.dev/get-dart#system-requirements

There is no separate list for where apps written with Dart may be run. And there are no levels of support for Dart (it's either or).

Flutter lists the platforms on which Flutter development are supported under the install docs, e.g.:
https://docs.flutter.dev/get-started/install/macos#system-requirements

And separately the platforms on which Flutter apps may be run/deployed, with several tiers here:
https://docs.flutter.dev/reference/supported-platforms

It would be nice to align this a bit.
