### ISSUE TITLE
Documentation problem with "Build and release an Android app": no "Generate Signed Bundle/APK" in Android Studio

### ISSUE THREAD

**Issue by tdkehoe** [flutter/website#6780]
## Steps to Reproduce

The documentation [Build and release an Android app](https://docs.flutter.dev/deployment/android#signing-the-app) says to create an upload keystore from Android Studio by 

```
In the menu bar, click Build > Generate Signed Bundle/APK.
```

I can't find this menu item in Bumblebee 2021.1.1.

**Comment by danagbemava-nc** [comment]
Hi @tdkehoe, there is a slight miscommunication in the doc.

You are supposed to open the `android` folder in "Android Studio", that is when the `Generate Signed Bundle/APK` will appear in the menu items. 

We should add a note in the documentation of that page so that users do not run into this issue.

**Comment by kyeshmz** [comment]
For those coming from google, I noticed that I had to configure the android framework for the `android` to appear with a logo and get `Generate Signed Bundle/APK` in the menu items

![Uploading Screen Shot 2022-08-22 at 11.08.48 PM.png…]()

**Comment by atsansone** [comment]
This text does not appear in the current page nor can it be found in the repo. Closing this issue.
