### ISSUE TITLE
CORS issue when requesting flutter website files from DevTools

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/website#6792]
Issue when requesting survey json file:
```
Access to XMLHttpRequest at 'https://flutter.dev/f/dart-devtools-survey-metadata.json' from origin 'http://127.0.0.1:9109' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Additionally, when developing the website and hosting through docker, we are seeing a CORS error when requesting the DevTools release notes files. So we get a CORS error when requesting the release notes markdown files through the localhost:4002 url, but we do not see the CORS error when requesting through the flutter.dev url.

**Comment by parlough** [comment]
I'm going to close this as the mentioned link is linking to `flutter.dev` instead of `docs.flutter.dev`, and our [`firebase.json`](https://github.com/flutter/website/blob/bd5331170602bf0f57d8260f7f11896fc2a561a3/firebase.json#L638-L641) is set up to add the appropriate headers.

The local case might not work still, but for these particular workflows I think relying on the automatic staged hosting is sufficient. If anyone feels like further work is needed here though, please let me know. Thanks!
