### ISSUE TITLE
[PAGE ISSUE]: 'Binding to native code using dart:ffi'

### ISSUE THREAD

**Issue by JulioCesarSF** [flutter/website#6801]
### Page URL

https://docs.flutter.dev/development/platform-integration/c-interop/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/c-interop.md

### Describe the problem

Hello,

With the recent release for Windows/linux desktop apps, I would like to ask if it is possible to create a wrapper for system calls (windows and linux) using this method?

The idea is to communicate with devices like: thermal printers, fiscal printers, barcode readers and others that requires you to load (LoadLibrary for Win32) a manufacturer's driver first.

The target platform is windows/linux in this case.

Is there a recommended package already done for this or an approach for this case?

Thanks,

**Comment by danagbemava-nc** [comment]
I'm not familiar with this topic to offer a good enough response to your question, but I believe your question belongs on other forums such as StackOverflow or any of the communities in https://flutter.dev/community#community-grid. 

You may not get much visibility over here as you would on maybe StackOverflow which I believe is the best place for this query. 

As such I'm going to have to close this issue since this forum is not for such support questions. 

Thank you
