### ISSUE TITLE
[PAGE ISSUE]: 'Writing custom platform-specific code'

### ISSUE THREAD

**Issue by dnparadice** [flutter/website#6856]
### Page URL

https://docs.flutter.dev/development/platform-integration/platform-channels/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/platform-channels.md

### Describe the problem

Cant resolve NoNull, embedding, or plugin for the imports:

import androidx.annotation.NoNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;

Flutter doctor returns: 

[✓] Flutter (Channel stable, 2.10.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[!] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

### Expected fix

1) Offer a solution to resolve dependency issues in demo project, even if that is a link to how to fix gradle or whatever is causing the dependency issue. 
2) Specify dependency tree for the demo project, for each of the required tools if flutter is not able to resolve these dependancies automatically. 
3) default flutter new project configuration is Kotlin but the example source on github is in Java so you cant see a kotlin version of the code.

**Comment by danagbemava-nc** [comment]
Hi @dnparadice, did you open the `android` folder and edit the `MainActivity.java`? Or were you in the root folder when you were seeing these errors?

**Comment by dnparadice** [comment]
Hello @danagbemava-nc, 

I am editing the kotlin file in the path: 
<repo>/batterylevel/android/app/src/main/kotlin/com/example/batterylevel/MainActivity.kt

that was generated using the command: 
>>> flutter create batterylevel

does this demo work for kotlin or only java? 

Thanks 
-Jayson

**Comment by danagbemava-nc** [comment]
> does this demo work for kotlin or only java?

Hi @dnparadice,
There's code for both of them. Kotlin is the default language for android so if you do not specify a language for `android`, that is what will be used. 

You need to open the `android` folder in `Android Studio` directly before you can properly edit the code in the `MainActivity.kt`

I assumed you were writing `java` because the imports you put in your issue description are terminated with `;` and that isn't necessary in kotlin.

> import androidx.annotation.NoNull;

This import is not correct btw

The doc outlines steps for you to open the android folder in android studio.

**Comment by dnparadice** [comment]
Hello @danagbemava-nc,
Thanks for the info. I am using android studio 4.2 as indicated in the original post, all editing is done in android studio 4.2 (see image). The reason I am here is because I followed the steps on the instructional page but the steps have an unsatisfactory result, If I knew everything about flutter I would not be here. So as a developer that is trying to learn flutter maybe we can fix this page together so it can help everyone that wants to learn flutter. 

The flutter create command does not generate a viable flutter project as described. After creating a project in flutter and proceeding through step 2 without issue. Step 3 (for kotlin) eventually says:

> Inside the configureFlutterEngine() method, create a MethodChannel and call setMethodCallHandler(). Make sure to use the same channel name as was used on the Flutter client side. 

And the following code is: 
```
import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity: FlutterActivity() {
  private val CHANNEL = "samples.flutter.dev/battery"

  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
      call, result ->
      // Note: this method is invoked on the main thread.
      // TODO
    }
  }
}
```
At this point in android studio the the imports can not be resolved. There is something missing here. Either I have a bad configuration somewhere or the 'flutter create' made a bogus project. So if the issue is that I have a bad configuration, I would like for the demo to let me know the versions required to run the demo so I can configure my system to match the required build tools. If the requirements for the demo are not stated I expect flutter to be able to use any version to make a viable project. 

You said that the imports I used are incorrect, but they are the imports stated on the demo page so I'm not sure what that means when you say that they are incorrect. I am trying to use the code on the demo page as stated. What is incorrect about the import? 

Thanks 
-Jayson 
<img width="1600" alt="Screen Shot 2022-03-02 at 6 48 05 AM" src="https://user-images.githubusercontent.com/37160154/156382732-4c5f1fa5-1f5f-4eba-a2a3-8e929996221c.png">

**Comment by danagbemava-nc** [comment]
Hi @dnparadice,

> You said that the imports I used are incorrect, 

In your initial post, the import was `import androidx.annotation.NoNull;` which is different from `import androidx.annotation.NonNull;` 


> At this point in android studio the the imports can not be resolved. There is something missing here. Either I have a bad configuration somewhere or the 'flutter create' made a bogus project. So if the issue is that I have a bad configuration, I would like for the demo to let me know the versions required to run the demo so I can configure my system to match the required build tools. If the requirements for the demo are not stated I expect flutter to be able to use any version to make a viable project.

This is because you are trying to edit an `android` project in a flutter project if that makes sense. What you need to do and is stated in the documentation is to open the `android` folder as a project on its own. 

![Screenshot 2022-03-03 at 09 20 02](https://user-images.githubusercontent.com/88313112/156534762-6f6742a4-95d2-4ddf-b036-f22695120d3d.png)

Also notice that in your screenshot the plugin shows an option for you to "Open for editing in android studio". That is because atm, the two projects are not entirely interoperable. See https://github.com/flutter/flutter-intellij/issues/4819


Kindly take a look at the screen recording below to see what I mean.


https://user-images.githubusercontent.com/88313112/156535520-3f22710a-7a77-45ac-92b5-ecc11d26175a.mov

**Comment by dnparadice** [comment]
Hello @danagbemava-nc, Awesome! Thanks for pointing out that you cant view an android project without errors in a flutter project (without changing a setting). It would be cool to have some reference to this issue in the example as it is not obvious that you can not just open the kotlin code in the flutter project. Based on the issue https://github.com/flutter/flutter-intellij/issues/4819
it would be reasonable to have the demo tell people to change the settings in android studio so they can see the kotlin and the flutter code in the same project.
