### ISSUE TITLE
[PAGE ISSUE] 'HomePage':  The content doesn't fit neatly on the screen on mobile

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [flutter/website#7094]
### Describe the problem

In [Flutter Homepage](https://flutter.dev/), after "Flutter is an open source framework...", the video/image has width of 125%.
Checking the style for the element shows `width: 125%`.
Setting width to 125% seems to be for desktops where the image should be bigger.
Seems like the style exists in https://storage.googleapis.com/cms-storage-bucket/main.9d18ed5a5baadba2e325.css.

### Expected fix

Make the image `width: 100%;` for only mobiles.

### Additional context

![flutter dev_](https://user-images.githubusercontent.com/78584173/166643982-fc1add61-698d-4a77-b3d3-07f74cc42005.png)

> In the image, the app bar's left side is hidden a bit and this is because the image is wider than the screen.

**Comment by danagbemava-nc** [comment]
I noticed that the content on the screen can shift left, this might be due to the video. 
A similar issue was raised before the site was updated to the new design in https://github.com/flutter/website/issues/3276

This was tested on a `Poco X3 NFC`.

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/88313112/166683871-905f3f75-62c4-42cd-9332-3584ca8249ab.mp4

</details>
