### ISSUE TITLE
'이전 화면에 데이터 반환하기' page issue

### ISSUE THREAD

**Issue by Abell-Choi** [flutter/website#7160]
Page URL: https://flutter-kr.io/docs/cookbook/navigation/returning-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/returning-data.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
Scaffold.of(context)... is not working at new flutter version..

Scaffold.of(context)
  ..removeCurrentSnackBar()
      ..showSnackBar(SnackBar(content: Text("$result")));

how about changing this
ScaffoldMessenger.of(context)
  ..removeCurrentSnackBar()
  ..showSnackBar(SnackBar(content: Text('$result')));

**Comment by danagbemava-nc** [comment]
Hi @Abell-Choi, unfortunately, the flutter-kr.io site is community maintained and we have no way of contacting the maintainers of the site, which is why the site is as outdated as it is. 

There isn't much we can do about that so I'm going to have to close this issue as the site is community-maintained. 

Thank you
