### ISSUE TITLE
Links to the official document are not working.

### ISSUE THREAD

**Issue by Jay-flow** [flutter/website#7307]
Go to the https://docs.flutter.dev/development/tools/hot-reload link and the links in the text shown in the picture below does not work.

The link to https://news.dartlang.org/2012/06/const-static-final-oh-my.html is dead.

![화면 캡처 2022-06-25 003041](https://user-images.githubusercontent.com/29420674/175568364-4fc61cc6-ed5b-4459-8519-d1239fa2edbe.png)
![화면 캡처 2022-06-25 003041](https://user-images.githubusercontent.com/29420674/175571150-f6b3453b-e51e-4da9-bbea-9b09028bb776.png)

![image](https://user-images.githubusercontent.com/29420674/175568857-91250b63-deb4-4ed8-a36b-8893317e9c7d.png)

**Comment by parlough** [comment]
Thanks for reporting this! There is a fix being prepared in https://github.com/flutter/website/pull/7308 but note the article link works, you just need to scroll further down the page to see the content due to some missing assets.

The old Dart blog still exists for historical purposes and potential improvements or alternatives are being tracked in https://github.com/dart-lang/site-www/issues/3917.
