### ISSUE TITLE
dart version issue

### ISSUE THREAD

**Issue by HarshaVoleti** [flutter/website#7334]
I have been facing dart version issues. whenever I'm running any project or adding additional packages to my flutter project. it shows the required package needs version 2.16.0 or above. I have recently updated my dart SDK to 2.17.0 still I'm getting this error. please, kingly reply me with the solution

**Comment by danagbemava-nc** [comment]
Hi @HarshaVoleti, this issue tracker is for reporting issues related to the flutter website. 

You should report the issue you're facing on StackOverflow or any of the communities in https://flutter.dev/community#grid so that you can get the help that you need. 

Closing as this is not the right forum to ask for help with these kinds of issues. 

Thank you
