### ISSUE TITLE
[PAGE ISSUE]: 'Internationalizing Flutter apps'

### ISSUE THREAD

**Issue by TarasBounty** [flutter/website#7382]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/internationalization/

### Page source

https://github.com/flutter/website/tree/main/src/development/accessibility-and-localization/internationalization.md

### Describe the problem

1. Open the https://docs.flutter.dev/development/accessibility-and-localization/internationalization#using-the-dart-intl-tools
2. Add `intl_translation` package to `pubspec.yaml`
3. Run `flutter pub get`

_Expected result:_ `intl_translation` added successful
_Actual result:_
`Because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0 and your-app-name depends on intl ^0.17.0, intl_translation >=0.17.7 is forbidden.
So, because your-app-name depends on intl_translation ^0.17.10+1, version solving failed.
pub get failed (1; So, because your-app-name depends on intl_translation ^0.17.10+1, version solving failed.)
exit code 1`

**Comment by danagbemava-nc** [comment]
Hi @TarasBounty, this is not an issue with this page but rather the `intl_translation` which has not been updated in a while. 

This issue has been filed on its repo https://github.com/dart-lang/intl_translation/issues/157. 

I think we could add a workaround until the package is updated, if there's any

**Comment by parlough** [comment]
Since both `package:intl` and `package:intl_translation` have been updated to support null safety in their 0.18 release, I'm going to close this. Please update to those new releases :)

Other updates to the internationalization page are in progress in https://github.com/flutter/website/pull/8065.

Thanks for opening the issue and the extra context! Let us know if you have any further issues :)
