### ISSUE TITLE
riverpod should be updated as the recommended default state management solution for Flutter instead of provider

### ISSUE THREAD

**Issue by csells** [flutter/website#7455]
### What information is missing?

On pages like [this one](https://docs.flutter.dev/development/data-and-backend/state-mgmt/options), [the provider package](https://pub.dev/packages/provider) is recommended as the state management solution. With [Remi planning to deprecate provider](https://twitter.com/remi_rousselet/status/1558799391280037889) in favor of [riverpod](https://pub.dev/packages/riverpod), the Flutter team shouldn't recommend something that has been deprecated.

### How would you like us to fix this problem?

1. [Work with Remi](https://github.com/rrousselGit/riverpod/issues/1561) to bring the docs and samples for riverpod up to the same level as provider.
2. Update [the website](https://docs.flutter.dev/) to replace provider with riverpod as the recommended state management solution.

**Comment by rrousselGit** [comment]
:wave:

Sorry, that was my fault for making that tweet.

Obviously, I wouldn't mind Riverpod getting the "recommended" status as Riverpod is my little baby. But objectively, I wouldn't do that yet unless the team truly wants to recommend Riverpod.  


Honestly, I didn't expect people to react to this tweet that much. It's not the first time I've mentioned I was considering deprecating Provider. It's been a topic since the release of Riverpod 2 years ago. Yet it's the first time people go as far as making Youtube videos & co about it 🙈 

But to be transparent: What recently changed is my motivation to remove the last few barriers for Riverpod to truly take over.
In particular, I'll do whatever it takes to fix https://github.com/flutter/flutter/pull/107112 & https://github.com/flutter/flutter/issues/106549.

I honestly believe that if these are fixed, there's no legitimate reason for Provider to exist. If they do get fixed, I'll 100% deprecate Provider.
The question is more about what if we can't fix those (due to them touching core elements).
So I wouldn't act on this issue until I've done the outcome of those issues isn't resolved.

**Comment by icnahom** [comment]
Why not leave that page for ChangeNotifier and AnimatedBuilder?

All other solutions can live freely, and developers will choose whatever they like.

**Comment by sfshaza2** [comment]
@timsneath, do you have advice on how to proceed with provider and riverpod?

**Comment by timsneath** [comment]
I'm not really the best placed to make a judgment here -- I'd defer to smarter folk like @johnpryan. 

What I understand from @rrousselGit is that:

- `provider` is not going away, but he's hoping that `riverpod` will ultimately supplant it
- he's planning to make it easier to migrate from one to the other
- there are some outstanding issues above that need resolution before `riverpod` is ready for even him to recommend it as the One True Solution (TM)

Meanwhile:

- `provider` is popular and there are many apps happily using it
- The `riverpod` documentation is still less comprehensive than `provider`
- There's no urgent need to act

As a result, I think the question is 'when', and the answer may be 'not yet'. But I'm just a product manager, I'm far less equipped to make the call on the timeline than others. Ideally we'd gradually build consensus first, and I don't know there's a fire drill here, is there?

**Comment by sfshaza2** [comment]
Definitely no fire drill! I gather that Twitter did have a bit of a fire, though.

**Comment by sfshaza2** [comment]
OK, this opened up numerous internal discussions. We aren't going to do this for now. Closing.
