### ISSUE TITLE
[PAGE ISSUE]: 'Build and release an iOS app'

### ISSUE THREAD

**Issue by nielscup** [flutter/website#7632]
### Page URL

https://docs.flutter.dev/deployment/ios/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/ios.md

### Describe the problem

What version is used when building ipa: version from `pubspec.yaml` or from info.plist?

1. when I only set the buildnumber in pubspec.yaml: I get the following error when running `flutter build ipa`:

`error: exportArchive: The provided entity is missing a required attribute: You must provide a value for the attribute 'cfBundleVersion' with this request`

### Expected fix

I would expect the version from `pubspec.yaml` to be used everywhere, as the default pubspec.yaml comment suggests.

### Additional context

This is what the pubspec.yaml comment says: 
In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.

**Comment by danagbemava-nc** [comment]
Hi @nielscup, what version of flutter did you experience this issue with? 

I tested a new counter app and I didn't get any issues when trying to build an ipa.

If possible, can you file a new issue on the main flutter repo and provide all the relevant information so that this can be investigated? 

Thank you
