### ISSUE TITLE
'Box Constraint 다루기' page issue

### ISSUE THREAD

**Issue by modooJH** [flutter/website#7680]
Page URL: https://flutter-kr.io/docs/development/ui/layout/box-constraints.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/box-constraints.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: The Korean translation of the Flex section is incorrect. It is totally wrong.
There is no way to reach MD file for the Korean version. I can not fix it by myself

**Comment by danagbemava-nc** [comment]
Hi @modooJH, unfortunately, the flutter-kr.io domain and it's content are community-maintained. 

The flutter website team is not associated with the project and unfortunately, we have no way of communicating with the maintainers of that domain. 

I'll be closing this issue since the site is community-maintained. 

Thank you
