### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by zzzh** [flutter/website#8072]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

1. The code in this part looks weird: "{step3_stateful_widget → step4_infinite_list}/lib/main.dart"

2. There's no code to display and add the favorite red heart.

### Expected fix

1. class _RandomWordsState should appear before class _RandomWordsState.
2. add the code to display and add the favorite red heart.

**Comment by parlough** [comment]
Hey @zzzh, thanks for opening the issue and adding suggested fixes.

This codelab has been removed and superseded by a new [Your first Flutter app](https://codelabs.developers.google.com/codelabs/flutter-codelab-first) codelab.

I believe the code to display and add the red heart was in step 5, which was in part 2, but both parts have since been taking down.

If you experience any issues with the new codelab or others, let us know. Thanks again!

**Comment by zzzh** [comment]
Hi, @parlough, thanks for replying.
I noticed the page change, seems it happened right after I commited this issue, looks like an automated action.
Interesting, seems someone had found the issue in the page and set this action instead of bring it up by him/her-self
