### ISSUE TITLE
Improve loading on slow networks

### ISSUE THREAD

**Issue by ManInTheWind** [flutter/website#8216]
### Page URL

https://docs.flutter.dev/

### Describe the problem

i think maybe the arrow icon of the catalogue act like this because of network speed?
[youtube video](https://www.youtube.com/shorts/pbWGZFBI-Gg)

**Comment by danagbemava-nc** [comment]
Hi @ManInTheWind, this is likely an issue with your network. 

Where are you accessing the website from? 

Can you check the chrome console to see if there are any errors?

**Comment by ManInTheWind** [comment]
Thanks for your reply. @danagbemava-nc 
Sure it is about the network.Might be the google font resource load not in time. But i think maybe the icon should have place holder or something? I dont know hahh.Because the icon label so long,If not should in time it will look like so wired.
Anyway,I just encountered it coincidentally. 
![image](https://user-images.githubusercontent.com/32859126/217264477-320bd358-3a64-4cbd-9d50-8d0c2349e2fd.png)

**Comment by danagbemava-nc** [comment]
Thanks for the info. We might have to improve how the assets are loaded on slow networks.

**Comment by parlough** [comment]
Thanks for opening the issue. Loading as text first is an accessibility feature so icons and buttons have a fallback during loading time or if they fail to load, rather than never showing up.

We are working on reducing the contents during loading, tracked in https://github.com/flutter/website/issues/8983 among other issues. When we work on https://github.com/flutter/website/issues/8984, we'll make sure to keep that fast as well. Hopefully that work will result in an overall improvement here.
