### ISSUE TITLE
Mistake in docs

### ISSUE THREAD

**Issue by Shivansh-yadav13** [flutter/website#8292]
### Page URL

https://docs.flutter.dev/development/ui/layout/tutorial

### Describe the problem

In "Step 2: Implement the title row"
the line "First, you’ll build the left column in the title section. Add the following code at the top of the build() method of the MyApp class:"

is wrong

### Expected fix

replace line 
```
First, you’ll build the left column in the title section. Add the following code at the top of the build() method of the MyApp class:
```
with

```
First, you’ll build the left column in the title section. Add the following code at the bottom of the build() method of the MyApp class:
```

**Comment by exaby73** [comment]
Hello @Shivansh-yadav13. This is correct, since as you can see that the code sample is making a variable called `titleSection`. Since the sentence is correct, this issue is invalid, and therefore I will close it. If you disagree with my decision, please comment with your reasoning and I can reopen the issue. Thank you
