### ISSUE TITLE
Android Compatibility 

### ISSUE THREAD

**Issue by amalbenny** [flutter/website#8294]
Can you please provide development compatibility of flutter from Android !
As per my best of knowledge it's limited to PC development environment.
![Screenshot_2023-02-23-08-49-16-44_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/119550625/220814478-49f26b8b-2d61-448a-90d2-170d2dbc71f4.jpg)

**Comment by danagbemava-nc** [comment]
Hi @amalbenny, the reason the current platforms are limited to desktop environments is because most of the tooling that flutter relies on are available only for desktop (or require desktop environments). You can try to set it up yourself for android by following https://medium.com/flutter-community/programming-on-your-phone-a2547f0e293 but it is not a trivial task.

I'll be closing this since the website page only shows what is capable currently, you can try requesting this feature be supported on the main flutter repo. 

Closing as this is not an issue with the website page. 

Thank you
