### ISSUE TITLE
Flutter Serious Issues

### ISSUE THREAD

**Issue by saleem81** [flutter/website#8406]
### What information is missing?

Facing keyboard lags/delay issue, unable to enter data in textfield in android released app mode, which dishearted me and no solution found anywhere. It will be good to provide online chat support where we can ask about problems we face in development and the solve it through direct chatting

### How would you like us to fix this problem?

Online developer chat support

**Comment by danagbemava-nc** [comment]
Hi @saleem81, kindly file an issue with the relevant steps to reproduce on the main flutter repo so that it can be investigated. Your issue will be responded to in a timely manner. 

> It will be good to provide online chat support where we can ask about problems we face in development and the solve it through direct chatting

The flutter team is active on [discord](https://discord.gg/BS8KZyg), slack and so are other members of the flutter community you can reach out to for support.

Closing as there are already channels that are available for support. 

Kindly file any issues you are facing on the flutter repo with enough detail to reproduce so that they can be investigated. 

Thank you
