### ISSUE TITLE
flutterfire configure does not list the projects of the account 

### ISSUE THREAD

**Issue by crysaro** [flutter/website#9260]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#2

### Describe the problem

flutterfire configure does not list the projects of the account  as stated in the docs:

> Configure FlutterFire
>
> You can use FlutterFire to generate the needed Dart code to use Firebase in your Flutter app.
>
> `flutterfire configure`
>
> When this command is run, you'll be prompted to select which Firebase project you want to use, and which platforms you want to set up.

Instead it automatically selected the "projects.default" value in the .firebaserc  which is the projects name and gave an error that it is not a valid id.

The command that worked is `flutterfire configure -p [theflutterproject-id]`

### Expected fix

Expected it to list the projects I have in my account and let me chose just like stated in the docs.

`flutterfire configure`

When this command is run, you'll be prompted to select which Firebase project you want to use, and which platforms you want to set up.

### Additional context

I am using Visual Studio Code in Ubuntu 22 LTS

**Comment by parlough** [comment]
Thanks for opening an issue and providing all of those details! I'm not familiar with flutterfire, but [in its code](https://github.com/invertase/flutterfire_cli/blob/117868d50758ee02ba2b8fcac19624310ffc1f6c/packages/flutterfire_cli/lib/src/commands/config.dart#L347C5-L347C22) it does seem to use the default project ID if one is specified like you experienced.

The instructions should either be modified to note this since the starting code [does specify](https://github.com/flutter/codelabs/blob/main/firebase-auth-flutterfire-ui/start/.firebaserc) a default, or remove that being specified as the default.

\cc @ericwindmill I'm not sure what the current plan is for this codelab, so I'm going to assign this to you. Thanks!

**Comment by sfshaza2** [comment]
I've pinged Eric directly and have asked him to triage and fix or close.
