### ISSUE TITLE
Android setup is too vague, just asks to install Android-Studio, not the specific tools

### ISSUE THREAD

**Issue by gintominto5329** [flutter/website#9413]
hi,

### Problem

- Go to [`docs.flutter.dev/install/linux#android`](http://docs.flutter.dev/get-started/install/linux#android-setup)
- It mentions "Download and install [Android Studio](https://developer.android.com/studio)."
- If someone do not want this 1.2 GBs (of mere garbage) in their computer, what should they do?

### Proposal

- Instead, the page should provide a list, of all the (needed) tools, like `cmdline-tools`, `platform-tools`, etc.
- Just like the [`docs.flutter.dev/install/linux#system-requirements`](http://docs.flutter.dev/get-started/install/linux#system-requirements) section.
```
 Tools: Flutter depends on these command-line tools being available in your environment.

    bash
    curl
    file
    git 2.x
    mkdir
    rm
    unzip
    which
    xz-utils
    zip

Shared libraries: Flutter test command depends on this library being available in your environment.

    libGLU.so.1 - provided by mesa packages such as libglu1-mesa on Ubuntu/Debian and mesa-libGLU on Fedora.
```

Note:  If this would increase complexity, then why is `system-requirements` showing the exact thing, we need in android-setup section.

thanking you

**Comment by danagbemava-nc** [comment]
Hi @gintominto5329, the reason the setup for android on linux (and other platforms) just states to install android studio is because the flutter tool is setup to work with android studio out of the box. It provides a straightforward experience for beginners since android studio has all the tools that are required for getting started with android studio. 

Regarding the setup for linux listing the requirements, I believe this is because various linux distros have different setups so informing users of what the tool requires is necessary. Nonetheless, we can add documentation on what is required if a user does not want to setup android studio. But do note that manually installing everything introduces more complexity in the setup process than installing only android studio.

**Comment by gintominto5329** [comment]
> manually installing everything introduces more complexity in the setup process

I understand this,

Cannot we add a "Basic, manual install" section, to "Help" button, of "Install Android Studio" among the existing:

- "Having multiple versions of Java installed",
- "`cmdline-tools` component is missing", etc

![Screenshot_20230919-190043-172.png](https://github.com/flutter/website/assets/82209141/13bc6151-b412-4447-8524-22a0f96b396d)

thanks

**Comment by atsansone** [comment]
This will be resolved when the Linux and ChromeOS install instructions are updated to match the macOS and Windows experiences. That said, to my understanding, the full install would still be required. Closing this for now.
