### ISSUE TITLE
Tutorial tv

### ISSUE THREAD

**Issue by Natanjkl21** [flutter/website#9814]

**Comment by huycozy** [comment]
Hi @Natanjkl21 
When opening an issue, please try to provide all information indicated in the appropriate template so that we can address this issue properly (See all issue templates [here](https://github.com/flutter/website/issues/new/choose)).

Closing this issue, since no information has been provided. Once you updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
