### ISSUE TITLE
hack

### ISSUE THREAD

**Issue by pavardemir** [flutter/website#9833]
### Describe the problem

hack android phone

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by pavardemir** [comment]
[](url)

**Comment by dam-ease** [comment]
Hi @pavardemir 
When opening an issue, please try to provide all information indicated in the appropriate template so that we can address this issue properly (See all issue templates [here](https://github.com/flutter/website/issues/new/choose)).

Closing this issue, since no information has been provided. Once you have updated the issue with more information, please write in the comments and I will re-open this for further discussion. Thanks!
